### ISSUE TITLE
Feedback from pandas-dev

### ISSUE THREAD

**Issue by MarcoGorelli** [pre-commit-ci/issues#10]
Hi Anthony,

I brought up with pandas-dev the idea of using pre-commit-ci. The feedback was that they wouldn't want a bot which automatically runs pre-commit on people's PRs (they brought up that, for new contributors, fetching new changes from the remote isn't such a trivial task), but instead would be open to using something which they could manually trigger with a comment, e.g.
```
/pre-commit-ci run
```
This way, if a PR is good to go except for some small linting issue, they could just write that in a comment and have it fixed.

I'm not making demands, just leaving this as feedback in case it's useful to you.

I've been using pre-commit-ci in my own project and so far it's awesome, I'll report back if I run into any issues

**Comment by asottile** [comment]
thanks for the message!

probably something that might be considered for enterprise / pro tier but probably not for free tier

**Comment by asottile** [comment]
btw it's implemented now, you can configure `ci: autofix_prs: false` and then comment "pre-commit.ci autofix" to manually run the fixing: https://pre-commit.ci/#configuration-autofix_prs

**Comment by MarcoGorelli** [comment]
Wow, thanks a ton for getting back to me on this!
