### ISSUE TITLE
2021-12-07 amazon us-east-1 outage

### ISSUE THREAD

**Issue by webknjaz** [pre-commit-ci/issues#102]
It's not present at https://results.pre-commit.ci/install/github/19541297 but the individual check pages like https://results.pre-commit.ci/run/github/320052445/1638908304.6WxAMIMoQ9a4wyTMD3HJQQ are available.
It's interesting that the check page shows a link to https://results.pre-commit.ci/repo/github/320052445 which returns 404.
I have a hunch that this may be connected to the fact that I added the repo to a pre-existing integration by navigating directly to https://github.com/apps/pre-commit-ci while not being authenticated on https://results.pre-commit.ci. But maybe it's a coincidence — I've also seen some 5xx error responses during my interactions over the past few hours so I can't be certain.

**Comment by asottile** [comment]
us-east-1 is currently burning in aws so there will be some inconsistency while that's down -- sorry for the inconvenience :(

**Comment by webknjaz** [comment]
No, problem, I'm not complaining, just wanted to notify :)

**Comment by asottile** [comment]
marking this all clear:

- I have re-queued the stuck runs (32)
- I have re-synced installations with github (815)
