### ISSUE TITLE
Possibility to add support for rust 2021

### ISSUE THREAD

**Issue by r0x0d** [pre-commit-ci/issues#103]
I believe the `Cargo` version used in pre-commit.ci is a bit old as it seems to not support Rust 2021 (https://doc.rust-lang.org/edition-guide/rust-2021/index.html). 

Is there any way to update the cargo/rust version for pre-commit.ci? Sorry if this is not the right place to ask, but I'm fairly new to the pre-commit.ci and do not know where to report such a thing. 

Run links that failed: 
* https://results.pre-commit.ci/run/github/438403315/1639526987.vekilUrtTkS58EAeOqiE9g
* https://results.pre-commit.ci/run/github/438403315/1639528193.D5ockXv1TvaddB-hBoII8Q

Thanks in advance.

**Comment by asottile** [comment]
feel free to send an update here: https://github.com/pre-commit-ci/runner-image/blob/f9c36eb2de1930499ba150f7787ffba936c448e8/Dockerfile#L108-L125

or perhaps this PR can be finished and then pre-commit can support `language_version` for rust for more flexibility: https://github.com/pre-commit/pre-commit/pull/1863

**Comment by r0x0d** [comment]
Sure, will do! Thanks!
