### ISSUE TITLE
Cargo can't reach github.com when installing dependencies

### ISSUE THREAD

**Issue by r0x0d** [pre-commit-ci/issues#104]
Bumped into this issue today. As it seems, Cargo can't reach github.com when downloading dependencies. 

This is the log run from pre-commit.ci: https://results.pre-commit.ci/run/github/440149929/1640205130.QDf9S0_ZS_-erKLha6eEMQ

In another time, I've bumped into another issue when installing dependencies with cargo:

* https://results.pre-commit.ci/run/github/440149929/1640194062.LephAwEqSgq0Q5euNQZTtw 

but this was easily solved by adding those 2 lines in my configuration: 

* https://github.com/r0x0d/merlin/pull/12/files#diff-9a4f3e4537ebb7474452d131b0d969d89a51286f4269aac5ef268e712be17268R1-R3

**Comment by asottile** [comment]
installation is only allowed at install time and not at run time

**Comment by asottile** [comment]
see also #29

**Comment by jpmckinney** [comment]
@r0x0d Your repository is either private or deleted. What two lines did you add to your configuration to avoid the error?
