### ISSUE TITLE
Autoupdate tries to downgrade to earlier version when specifying a commit

### ISSUE THREAD

**Issue by DanielNoord** [pre-commit-ci/issues#110]
_Please let me know if this isn't the correct repo for these issues!_

Relevant PR is: https://github.com/PyCQA/pylint/pull/5808 and commits can be seen here: https://github.com/DanielNoord/pydocstringformatter/commits/main
We have set the version of `pydocstringformatter` to a commit after the `0.4.0` release as it included a small bug for which a new release has not yet been published. Autoupdate opens a PR to "upgrade" to `0.4.0` even though we're on a later commit.
Would it be possible to make autoupdate check which commit is associated with the tag it tries to update to and then check if the current specified commit is of a later date?

**Comment by asottile** [comment]
this is just how autoupdate works.  I would recommend making a tagged release since you control all the parts
