### ISSUE TITLE
Feature request: badge preview and code

### ISSUE THREAD

**Issue by eggplants** [pre-commit-ci/issues#116]
I have just implemented this feature with userscript: https://greasyfork.org/en/scripts/442493
![l9h030u92nxaf6mku71tv7a86mrx](https://user-images.githubusercontent.com/42153744/161342120-8df38c18-bdb7-4316-8ba9-90f816886d2c.png)

On the top of the result page, I would like to add badge preview and code to copy and paste to the project documentations.

Could you support this officially?

Thanks.

**Comment by asottile** [comment]
there's no need -- it's listed in the project itself: https://results.pre-commit.ci/repo/github/17689377

it would just clutter the result page

**Comment by eggplants** [comment]
Oh, I overlooked. Thank you for your answer!
