### ISSUE TITLE
Undescriptive error message

### ISSUE THREAD

**Issue by ooliver1** [pre-commit-ci/issues#120]
https://results.pre-commit.ci/run/github/400793998/1651006768.uMUW6SSaRSSlM-LnRASAqQ

im unsure as to what the issue here is, does the config need to be on `master` for the ci to take place?

**Comment by asottile** [comment]
which part are you confused about?  I can elaborate and improve based on specific feedback but as of right now I'm not sure what you're confused about?

**Comment by ooliver1** [comment]
![image](https://user-images.githubusercontent.com/34910574/165539017-4bd97eaa-831a-4f20-ba04-6f16ed015192.jpeg) this output isn't very descriptive on what the issue was

**Comment by asottile** [comment]
pre-commit ci tries to fix your PR for you, but it couldn't because there was a conflict

did you try doing what it asked you to do?

**Comment by ooliver1** [comment]
Oh right, it was a bit vague on what it meant

**Comment by asottile** [comment]
it gives you a direct thing to try and you didn't do it?
