### ISSUE TITLE
would prefer not to upgrade to pre-releases

### ISSUE THREAD

**Issue by jepler** [pre-commit-ci/issues#124]
I have a PR opened by pre-commit-ci to upgrade pylint to an unstable (beta) release: https://github.com/jepler/Jepler_CircuitPython_udecimal/pull/14

I would prefer that pre-commit-ci not propose upgrades to unstable versions of software used in checks.

**Comment by asottile** [comment]
pre-commit.ci just runs `pre-commit autoupdate` -- `pre-commit autoupdate` just uses "latest git tag" -- there's a few duplicates in pre-commit/pre-commit -- this being the easeist one I could find: https://github.com/pre-commit/pre-commit/issues/995
