### ISSUE TITLE
`'pkg-config' not found.`

### ISSUE THREAD

**Issue by eggplants** [pre-commit-ci/issues#126]
https://results.pre-commit.ci/run/github/364638362/1654366597.Qqhy2XKRRva-vl_Yve79Rg

My project needs [PyGObject-stubs](https://github.com/pygobject/pygobject-stubs) to lint with mypy. It also needs `PyGObject` and its dependencies including `pycairo`.

While building pycairo in pre-commit.ci, it raises `'pkg-config' not found.` Error.

Any workarounds?

**Comment by asottile** [comment]
hmmm I would probably assert that `pygobject-stubs` is set up incorrectly and shouldn't depend on `pygobject` -- even if I were to add `pkg-config` it would then next fail on missing `cairo` (which is a very hefty dependency)
