### ISSUE TITLE
pre-commit ci fails to commit changes after running via a main branch commit

### ISSUE THREAD

**Issue by EmmmaTech** [pre-commit-ci/issues#129]
Hello, so I recently installed the pre-commit-ci application into my repo. So I opened a PR to add in the config file and the changes from the linting. It was able to commit the changes successfully according to this run: https://results.pre-commit.ci/run/github/459859496/1655513496.UVSsOOzgTt2tY1IVTIdjxg

However, after the PR was merged and I tried to do it again with a normal commit to the main branch, it ran and failed as expected, but then it skipped over the committing changes step according to this run and various others afterwards: https://results.pre-commit.ci/run/github/459859496/1655521956.DV3lbe6PQkOAdJ_0WJo7oQ

So my question is: is this intentional behavior? Because it seemed to work fine for a non-main branch, but not the main branch itself.

**Comment by asottile** [comment]
yes, pre-commit ci will never touch a non pull request branch -- it always gives the user a chance to verify the changes made automatically
