### ISSUE TITLE
Feature request: Automatic updates without the continuous integration?

### ISSUE THREAD

**Issue by peterjc** [pre-commit-ci/issues#131]
*Request*: Could we disable the continuous integration on pre-commit.ci (i.e. ignore new commits and PR), but still have pre-commit.ci make PRs to update the dependencies in ``.pre-commit-config.yaml``?

*Use case*: Systems where running all the checks in ``.pre-commit-config.yaml`` (often) exceed the 3 minute limit on pre-commit.ci, and are therefore being run elsewhere (e.g. GitHub Actions, CircleCI, TravisCI, etc). See e.g. https://github.com/biopython/biopython/issues/3958 

*Workaround*: Use ``skip: [...]`` to skip (almost) all the hooks, so that pre-commit.ci runs (almost) no hooks.

*Suggestion*: Introduce ``skip: [*]`` or similar as the syntax for this request.

**Comment by asottile** [comment]
`skip` is the intended mechanism for this

**Comment by peterjc** [comment]
OK, so we'd just need a (long) multiple-hook skip entry. Thanks!
