### ISSUE TITLE
StyLua hook fails to install on CI but installs fine locally

### ISSUE THREAD

**Issue by rocode** [pre-commit-ci/issues#132]
Error Log: https://results.pre-commit.ci/run/github/508851157/1656543590.xcSTk2xARCumYXsJFkxGyw

Relevant `.pre-commit-config.yaml` section:

```yaml
-   repo: https://github.com/JohnnyMorganz/StyLua
    rev: 0f3f33c15f569130131eee3e54b73515afd2b3aa  # frozen: v0.13.1
    hooks:
    -   id: stylua-github

**Comment by asottile** [comment]
that'd be a bug in `release-gitter` it looks like

this code: https://git.iamthefij.com/iamthefij/release-gitter/src/branch/main/release_gitter.py#L144 is python 3.9+ syntax cc @iamthefij

they could fix it by adding `from __future__ import annotations` on that file

alternatively you can set `language_version: python3.9` to force an installation with a newer version of python (pre-commit.ci [currently defaults to python3.8](https://github.com/pre-commit-ci/runner-image/blob/6282d06379ccd504204ccd68a4543b437f31a41a/versions.md#python))

**Comment by rocode** [comment]
WIth `language_version: python3.9` and `language_version: python3.10`:

Forward progress, new issue: https://results.pre-commit.ci/run/github/508851157/1656610019.aRVtVbKQRt-wmJViMfqKSg

`OSError: [Errno 18] Invalid cross-device link: '/pc/clone/QS-gDmx1QpG9ZloEk2_gYA/stylua' -> '/tmp/pip-wheel-rfs4j2kd/pseudo-0.13.1.data/scripts/stylua'`

It looks like this fails because `/pc/` and `/tmp/` are different mounts? @asottile

**Comment by asottile** [comment]
yep -- that would be another bug in release-gitter which currently assumes that the wheel build directory and the temporary filesystem are on the same mount -- this is also not a pre-commit.ci issue and something you should take to @IamTheFij

**Comment by IamTheFij** [comment]
Thanks @asottile for tagging me. I'll create a mirror of the project on GitHub so @rocode can open an issue there.
