### ISSUE TITLE
Document default value of the Python language_version somewhere

### ISSUE THREAD

**Issue by DanielNoord** [pre-commit-ci/issues#136]
Thanks for all the work you do!

I noticed you bumped the default version of the Python language version and announced this via the mailing list ([here](https://groups.google.com/g/pre-commit-ci/c/7o-vBuk6C64)). However, I don't think many users are subscribed to the mailing list and might have missed that announcement.
The bump broke our `main` branch and I can imagine it will for others as well.

I looked in the `pre-commit` and `pre-commit-ci` repositories but couldn't find a commit or documentation that reflects this change or the default value.
Would it be possible to document this somewhere? For example by printing the configuration file being used by `pre-commit.ci` in the `ci config` step?

**Comment by asottile** [comment]
you're looking for https://github.com/pre-commit-ci/runner-image
