### ISSUE TITLE
autofix of github actions files fails

### ISSUE THREAD

**Issue by ksunden** [pre-commit-ci/issues#14]
For this run: https://results.pre-commit.ci/run/github/33698232/1604554212.vvLOPmhDTZmWff-LgShd2A

I had two hooks fail (As I just updated black version and added the trailing whitespace hook), and I was expecting to get the auto commit, but did not.

I ran and committed one of the hooks locally, and then the auto commit worked on the next run (for which only black made changes).

Is this expected behavior?

I actually think my preferred behavior would be one commit _per hook_, which would make it easy to tease out what happened in code review (though hopefully pre commit hooks aren't doing things that break...)

PS, I am loving precommit ci so far, the auto commit feature in particular... why just have a bot _tell_ you something is wrong, when you can have it just fix it for you. Also serves as a reminder to run pre-commit install locally on the dev machines, something I find myself forgetting to do on fresh clones from time to time)

**Comment by asottile** [comment]
I actually have a TODO for this, haven't gotten around to it -- github has special permissions for actions files -- this is the same issue that's plaguing my deadsnakes nightly builds too: https://github.com/deadsnakes/issues/issues/130

![Screenshot from 2020-11-04 22-10-02](https://user-images.githubusercontent.com/1810591/98204254-8b1c4b80-1eea-11eb-8854-d2a98e6ee86f.png)

fortunately, it's fixable here -- I just need to give the app permission to "Manage actions" (which will require a permissions update on those with the app installed)

```diff
$ git rev-parse HEAD
e117134e5129c4244feb680b60d585214beda57f
$ git diff -- .github/workflows/
diff --git a/.github/workflows/codeql-analysis.yml b/.github/workflows/codeql-analysis.yml
index bae9c6b..ed8ad7c 100644
--- a/.github/workflows/codeql-analysis.yml
+++ b/.github/workflows/codeql-analysis.yml
@@ -47,7 +47,7 @@ jobs:
       with:
         languages: ${{ matrix.language }}
         # If you wish to specify custom queries, you can do so here or in a config file.
-        # By default, queries listed here will override any specified in a config file. 
+        # By default, queries listed here will override any specified in a config file.
         # Prefix the list here with "+" to use these queries and those in the config file.
         queries: +security-and-quality
 
```

**Comment by ksunden** [comment]
Ahh, matter of _which_ file was touched, not the fact that there were two tests... makes sense (luckily those files are not touched very often)

**Comment by asottile** [comment]
you should get a permissions request soon which looks like this:

> - 2020-11-04: **Added: GitHub Workfows Read+Write** - this is necessary to autofix PRs which have fixable issues in `.github/workflows/*` files

I'm rolling out the backend changes right now (a bit of a chicken-and-egg problem)

**Comment by ksunden** [comment]
I did indeed get that

**Comment by asottile** [comment]
this should be resolved now -- thanks for the report!
