### ISSUE TITLE
Failing to access external links as part of markdown-link-check pre-commit hook

### ISSUE THREAD

**Issue by pankajkoti** [pre-commit-ci/issues#141]
hi, I am trying to use the https://github.com/tcort/markdown-link-check to check for 
dead links in our .md files.
The hook runs all fine when run locally & also from within CirceCI. But, when it is
run as part of the pre-commit-ci run, it complains saying that none of the links are active.
Is it a case that the CI does not allow making requests to external links?

Here is the outcome of one such failure job run: https://results.pre-commit.ci/run/github/388913563/1660721464.FXCn6PqETH2lUdwLRetY4A

**Comment by asottile** [comment]
there is no network allowed at runtime see #55

**Comment by pankajkoti** [comment]
Thanks @asottile for the quick response 👍🏽
