### ISSUE TITLE
Java language support

### ISSUE THREAD

**Issue by junghoon-vans** [pre-commit-ci/issues#142]
Hooks using `java` or `coursier` do not currently work on pre-commit ci.
I want to use pre-commit ci in JVM environment. Do you have any plans to support?

**Comment by asottile** [comment]
yeah eventually -- you can expedite the process by contributing it to https://github.com/pre-commit-ci/runner-image

**Comment by junghoon-vans** [comment]
Thank you for your answer. I'll try contributing for java support.
