### ISSUE TITLE
Signed-off-by / DCO line

### ISSUE THREAD

**Issue by tykeal** [pre-commit-ci/issues#144]
I'm always having to fix the auto update PRs because my projects all require a Signed-off-by (aka DCO) line. For some reason the DCO probot always flags it as valid, but I've got a check that does some "magic" to make pre-commit commit message validation work and gitlint always fails the check.

**Comment by asottile** [comment]
you'll need to provide more details, it's unclear what you're asking for but it sounds like this is a gitlint feature request?

**Comment by tykeal** [comment]
No, it's not feature request for gitlint itself. I'm asking for a way to configure the CI bot to add a Signed-off-by footer in the commit messages that it produces. They fail validation that gitlint is doing for me.

**Comment by asottile** [comment]
you'll need to show more information I still have no idea what you're talking about

**Comment by tykeal** [comment]
Here's what I end up having to do when I get an auto-update PR from the bot [tykeal/homeassistant-rental-control#123 ](https://github.com/tykeal/homeassistant-rental-control/pull/123/commits/fb9c1720de5d8e85059b30a3e6e0119b4e53fec0)

Note the footer of the commit message:

```
Signed-off-by: Andrew Grimberg <tykeal@bardicgrove.org>
```

This is done automatically for you when you issue a '-s' to git commit

My personal repositories as well as literally 100% of every other open source (and non-open) repository I work with all have hard requirements on this DCO line existing. The meaning behind it can be found here: https://developercertificate.org/

**Comment by asottile** [comment]
the autoupdate commit message is customizable -- feel free to add your DCO to it https://pre-commit.ci/#configuration-autoupdate_commit_msg

**Comment by asottile** [comment]
a bot itself cannot DCO -- the commits are signed though which is why probot is ok with it -- your tooling is the issue here I suspect since it doesn't recognize signed commits

**Comment by tykeal** [comment]
> the autoupdate commit message is customizable -- feel free to add your DCO to it https://pre-commit.ci/#configuration-autoupdate_commit_msg

I have that set, all it does is modify the commit subject line. None of the rest of the commit message.

**Comment by asottile** [comment]
```yaml
    autoupdate_commit_msg: |
        subject here

        Signed-off-by: Andrew Grimberg <tykeal@bardicgrove.org>
```

seems to work for me?

**Comment by tykeal** [comment]
Hmm... I'll give it a try. I was honestly expecting that when I set it that it wouldn't add in the the updated modules information. I sort of expect that it will still end up adding the update module information into the commit thereby breaking this in a different way since SBO is supposed to be a footer.

**Comment by asottile** [comment]
rather than assuming just try it ! otherwise you're wasting both of our times :P
