### ISSUE TITLE
Executable not found

### ISSUE THREAD

**Issue by jab** [pre-commit-ci/issues#148]
Just tried pre-commit.ci for the first time and got an unexpected `Executable not found error` for one of my hooks, namely pyright: https://results.pre-commit.ci/run/github/24373694/1666543909.r2gHWMm5SpejehNcqe-h5g

I cannot reproduce locally nor in GitHub Actions where I am using the `pre-commit` action. For example, here is a GitHub Actions pre-commit run from a few minutes ago where the `pyright` hook succeeds:
https://github.com/jab/bidict/actions/runs/3307833593/jobs/5459766105#step:6:121

**Comment by asottile** [comment]
you're using `language: system` for pylint (which is the unsupported escape hatch for pre-commit and also pre-commit ci).  for pyright you've correctly set `language: node` but you're missing `additional_dependencies` to actually install pyright

**Comment by jab** [comment]
Thanks for the quick reply!

Didn't realize `language: system` was unsupported by pre-commit.ci. Would it make sense to try to make this more obvious to users of the service? E.g. Currently users just see an error message like "Executable `pylint` not found". An error like "language: system is not supported" would be clearer for users, especially when this doesn't reproduce locally or on GitHub Actions.

Maybe pre-commit.ci should somehow try to warn users about this more prominently ahead of time? (This way users who can't give up hooks like pylint won't waste your resources by trying pre-commit.ci before realizing they can't use it.)

Hope this helps, and thanks again.

**Comment by asottile** [comment]
it's not specific to pre-commit.ci -- you'll see exactly the same error message locally -- for instance when I check out your repo and run pre-commit I see exactly what pre-commit.ci sees

**Comment by jab** [comment]
Right, you have to run pre-commit via “tox -e lint” for my project if you
want the pylint hook to work. But something like that is true for any
project using the pylint hook, and so I guess a “language: system”-specific
addition to the “executable not found” error message would help locally too?
