### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by rphlo** [pre-commit-ci/issues#149]
I have
```
default_language_version:
  python: python3.11
```
in my .pre-commit-config.yaml file and pre-commit.ci online runner fails with 
`RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.11'`
While the pre-commit hook pass on local with python3.11 installed

**Comment by asottile** [comment]
it'll be rolled out later today. ran into an issue with the latest [runner image](https://github.com/pre-commit-ci/runner-image) that I need to fix due to a breaking change in `git`
