### ISSUE TITLE
Attempting to "upgrade" poetry from 1.2.2 to 1.2.0rc1

### ISSUE THREAD

**Issue by ChrisLovering** [pre-commit-ci/issues#152]
I am not sure of the cause, but pre-commit.ci is attempting to "upgrade" poetry from 1.2.2 to 1.2.0rc1

https://github.com/owl-corp/python-template/pull/10

**Comment by asottile** [comment]
https://github.com/pre-commit/pre-commit/issues?q=is%3Aissue+poetry+is%3Aclosed

poetry doesn't tag their primary branch so they are incompatible with autoupdate
