### ISSUE TITLE
R language local hooks

### ISSUE THREAD

**Issue by lorenzwalthert** [pre-commit-ci/issues#154]
I don't know why yet, but it seems pre-commit.ci supports local hooks and at least one of mine does not work (`language: r`, so it should be supported I assume). It also [used to work with these hooks](https://github.com/lorenzwalthert/precommit/pull/453). Is it possible to give more context on the second build attempt for debugging? E.g. changing the default debugging level for stout? Or print the log at the end (since I think the log file is not accessible for me now)?

<img width="1205" alt="Screenshot 2022-12-28 at 11 14 13" src="https://user-images.githubusercontent.com/10477073/209796238-144e7b12-451f-4ebd-a12c-5ef782d97bbc.png">

https://results.pre-commit.ci/run/github/186313720/1672179163.5jOhdqgoR2CNwIMznDBmSA

**Comment by asottile** [comment]
oh oops I might have broken this. I think I only copy the top level of the local repo

**Comment by asottile** [comment]
https://github.com/pre-commit-ci/runner-image/pull/179 should fix it

**Comment by asottile** [comment]
looks like it's working now! thanks for the report

**Comment by lorenzwalthert** [comment]
Thank you for the quick fix.
