### ISSUE TITLE
Is pre-commit.ci supposed to be running on push events (not pull requests)?

### ISSUE THREAD

**Issue by trallnag** [pre-commit-ci/issues#155]
In one of my repos I started to use pre-commit.ci and I noticed that it runs on ordinary pushes to the master branch without any pull requests involved. Is this supposed to happen?

Looking at the homepage <https://pre-commit.ci/> I am only reading that it runs on pull requests.

Here is the commit where pre-commit.ci was triggered: https://github.com/trallnag/kubestatus2cloudwatch/commit/6840390c5fbc3767a25fec84520af8f78515cbb5

**Comment by asottile** [comment]
yes, it will run on the primary branch -- but it will never push to the primary branch (only to pull requests)

**Comment by trallnag** [comment]
ok thanks for clarification
