### ISSUE TITLE
Debugging autofix / truncated output

### ISSUE THREAD

**Issue by max-sixty** [pre-commit-ci/issues#158]
Hi there!

I'm trying to debug why there wasn't an autofix on a commit, and then why requesting an autofix didn't work:

Some context:
- Here's the ci page: https://results.pre-commit.ci/run/github/449091292/1673683965.3RuJGXjYQcyhzbEBAQjxFg
- Here's the commit: https://github.com/PRQL/prql/pull/1500/commits/be7fc7a32b0035928ed3cd932d6da6acce4fb489
- I've had this issue with prettier in CI where it seems to just list every file!
  <img width="1326" alt="image" src="https://user-images.githubusercontent.com/5635139/212464494-f6c16957-51ec-4eb3-8a28-05b991d32b08.png">
- Running `pre-commit run -a` locally on that commit yields a very reasonable output:
  <img width="653" alt="image" src="https://user-images.githubusercontent.com/5635139/212464532-7425ffda-8549-4df0-ba35-690b82cf448e.png">

I then added `pre-commit autofix` [here](https://github.com/PRQL/prql/pull/1500#issuecomment-1382688921), and got a 🚀, but no commit. Two minutes later I then [pushed the changes myself](https://github.com/PRQL/prql/pull/1500/commits/8ab550e238fa2a139e3859906336ef976fe30628); possibly I should have waited for longer?

If there's a way for me to debug this without raising an issue, that would be awesome.

Thanks a lot as ever

**Comment by asottile** [comment]
github blocked all apps from making changes to workflow files (even though the permission is enabled for pre-commit ci) -- I have a year old ticket with them that they have not followed up on

as for prettier's output I have no idea, they do some wild things. you can try the docker image that's listed in your run

**Comment by max-sixty** [comment]
Great thanks!

**Comment by asottile** [comment]
pushes which fail in this way will now produce a message on the run: "GitHub prevented pre-commit.ci from autofixing this pr due to autofixes to a workflow file"

**Comment by max-sixty** [comment]
Awesome! Thanks @asottile !
