### ISSUE TITLE
pre-commit CI times out while installing mypy

### ISSUE THREAD

**Issue by Saransh-cpp** [pre-commit-ci/issues#159]
I am seeing the pre-commit CI timeout while installing mypy in multiple projects. Rerunning the CI does not solve this issue, and I have no idea from where this is originating.

| Bot PR | Failing build |
|-|-|
| https://github.com/Saransh-cpp/riemapp/pull/45 | https://results.pre-commit.ci/run/github/540904220/1673892067.cqVMlW2WQT2ON4iXI6Xl4Q |
| https://github.com/Saransh-cpp/OCRed/pull/98 | https://results.pre-commit.ci/run/github/517398089/1673892047.t8w3X0wyRb6C8DnQSzd7YQ |
| https://github.com/scikit-hep/vector/pull/306 | https://results.pre-commit.ci/run/github/217698030/1673774921.Uc6xN5nAQY6RiMYEYqJKTQ |

A random (but the same) issue I found while looking for a fix - [scverse/spatialdata#94](https://github.com/scverse/spatialdata/issues/94).

Could someone please let me know why this is happening?

Thanks!

**Comment by asottile** [comment]
given [this](https://github.com/Saransh-cpp/riemapp/blob/f83ee15a0e4b9a2cf136945996bc715c342b9995/.pre-commit-config.yaml#L92-L94) then #157 is an exact duplicate

**Comment by Saransh-cpp** [comment]
Ah, you beat me to it! I was just reading the same issue! Will try, thanks!
