### ISSUE TITLE
Manually override cache in CI jobs

### ISSUE THREAD

**Issue by gipert** [pre-commit-ci/issues#160]
My pre-commit CI jobs are suddenly failing because of a [new check introduced by flake8-bugbear](https://github.com/PyCQA/flake8-bugbear#23114), despite Flake8's version staying constant. The new behavior was then promptly reverted in a [second release](https://github.com/PyCQA/flake8-bugbear#23117). My (possibly wrong) interpretation is that [the CI job](https://results.pre-commit.ci/run/github/151981074/1674041440.W7YiqLveQOueD7Bx1aBlrA) is still failing (contrary to what happens locally) because of a caching issue.

I was wondering whether there is a way to manually override the cache in CI. I could not find any reference in the docs.

**Comment by asottile** [comment]
you can pin a version and your cache will be consistent

**Comment by gipert** [comment]
I did not know I could pin a specific flake8-bugbear version. Works now thanks!
