### ISSUE TITLE
[feature] Can pre-commit-ci robot respect file mode?

### ISSUE THREAD

**Issue by Freed-Wu** [pre-commit-ci/issues#161]
I add a shebang to `.pre-commit-config.yaml` to allow me to replace `pre-commit run -a` with `./.pre-commit-config.yaml` which is more easy to input (just press `./.p<TAB>`).

```sh
#!/usr/bin/env -S pre-commit run -ac
```

However, pre-commit-ci changes the file mode `x`.

![screen-2023-01-18-20-57-51](https://user-images.githubusercontent.com/32936898/213178270-5c454936-6c2d-46a4-b2dc-4dc2f03f9d38.jpg)

Can it respect the file mode? TIA!

**Comment by asottile** [comment]
that file should not be executable by convention

**Comment by Freed-Wu** [comment]
But, even if this file is not `+x`, the PR from pre-commit.ci still should respect the file mode, for example, if `.pre-commit-config.yaml` is `rw-rw-rw-`, the PR shouldn't change it to `rw-r--r--`, I think.

**Comment by asottile** [comment]
yes I understand, but you're doing something pretty weird and I don't want to write special code to support such a weird case when it's a common mistake to make the file executable

**Comment by Freed-Wu** [comment]
> you're doing something pretty weird

I know.

> if .pre-commit-config.yaml is rw-rw-rw-, the PR shouldn't change it to rw-r--r--.

How about this? I think it is reasonable.

**Comment by Freed-Wu** [comment]
> you're doing something pretty weird

I know. (A weird hack :smile:)

> if .pre-commit-config.yaml is rw-rw-rw-, the PR shouldn't change it to rw-r--r--.

How about this? I think it is reasonable. Because in some situation, umask is not 022. We should not break it.

**Comment by asottile** [comment]
git doesn't store the rest of the umask -- git only has modes 0644 and 0755 -- it already isn't going to change 0666 to 0644 because that doesn't mean anything to git
