### ISSUE TITLE
Document force push behaviour of pre-commit autoupdates?

### ISSUE THREAD

**Issue by Zeitsperre** [pre-commit-ci/issues#162]
With precommit.ci configured to make automatic pull requests in my repositories, if the PR is modified by a user and is not merged before the next scheduled update, the pre-commit CI bot will force push updates to the commit that opened the PR and remove all subsequent commits made.

I came across the relevant issue #49 here, but I was unaware that this could occur (it did not set me back very long, thankfully), so I was thinking it would be helpful to make a mention of this behaviour in the documentation ("Warning", "Gotchas")?

**Comment by asottile** [comment]
#49 is a duplicate

yeah I'm not really sure there's anything actionable here -- the branch is "owned" by pre-commit so it shouldn't really be much of a surprise (github also will always show you the original commit id so you can always recover the original changes anyway) -- so at most it's an "inconvenience" and it'll never lose changes --
