### ISSUE TITLE
RuntimeError: The Poetry configuration is invalid

### ISSUE THREAD

**Issue by gipert** [pre-commit-ci/issues#163]
CI jobs are suddenly failing:

https://results.pre-commit.ci/run/github/151981074/1675076029.uIZOilWBRR2WZ842BQP4NQ

without any change in the config file.

**Comment by sanders41** [comment]
I am seeing this also

**Comment by jeertmans** [comment]
Plus one on this, same failure: https://results.pre-commit.ci/run/github/513032928/1675084116.Jyte5SuFS5e0cQ75tbqD6A.

**Comment by asottile** [comment]
search the internet or the issue tracker for duplicates please

**Comment by bjlittle** [comment]
@gipert @sanders41 and @jeertmans rather than searching the internet, see #164, specifically this [comment](https://github.com/pre-commit-ci/issues/issues/164#issuecomment-1408737936)

HTH

**Comment by jeertmans** [comment]
Thanks @bjlittle
