### ISSUE TITLE
pre-commit.ci preparing metadata failure

### ISSUE THREAD

**Issue by bjlittle** [pre-commit-ci/issues#164]
Hi @asottile !

Thanks for `pre-commit.ci`, it's fantastic! :smile: 

Unfortunately, I'm experiencing an issue with `pre-commit.ci` during the `Preparing metadata` step. 

Specifically, see [this pre-commit.ci log](https://results.pre-commit.ci/run/github/366434296/1675067316.dQohgAJUQGyylzhprEW4Hg) for [geovista](https://results.pre-commit.ci/repo/github/366434296).

I've not made any changes to my repo package dependencies or `.pre-commit-config.yaml` nor `pyproject.toml`, and prior CI runs were operational yesterday (30 Jan 2023).

I noticed that there was a patch release of `pre-commit` [v3.0.2](https://github.com/pre-commit/pre-commit/releases/tag/v3.0.2) a few hours ago... could this be related to the failure that I'm experiencing? Not sure how to move forwards to resolve this. Can you help?

Hope you can help diagnose and advise?

Many thanks :+1:

**Comment by Guts** [comment]
Same issue here, every runs are failing:

- https://results.pre-commit.ci/repo/github/248722492
- https://results.pre-commit.ci/repo/github/59329370

**Comment by asottile** [comment]
search the issue tracker or the Internet for duplicates please

**Comment by bjlittle** [comment]
See https://github.com/PyCQA/isort/issues/2077

**Comment by bjlittle** [comment]
Ping @Guts 

For those that follow, the fix is to set the version of the `isort` pre-commit hook to as least `5.12.0` in your `.pre-commit-config.yaml` :+1:

**Comment by Guts** [comment]
> search the issue tracker or the Internet for duplicates please

The search leaded me to this issue :wink: .

> Ping @Guts
> 
> For those that follow, the fix is to set the version of the `isort` pre-commit hook to as least `5.12.0` in your `.pre-commit-config.yaml` +1

Thanks a lot @bjlittle, I've already seen the fix and started to apply it.
