### ISSUE TITLE
Previously working hook fails since local executable can't be found

### ISSUE THREAD

**Issue by lorenzwalthert** [pre-commit-ci/issues#165]
My local R hook that worked on pre-commit.ci and works locally with `entry_point: Rscript inst/hooks/local/hooks-config-to-inst.R` does apparently not work anymore, as the corresponding executable in the cloned repo is not found anymore: https://results.pre-commit.ci/run/github/186313720/1675013388.2JJTn3qtTbK7thcVWBMD5g. Any ideas why?
```bash
Fatal error: cannot open file '/pc/clone/a2Kw-5FAQIyJz2B3MzJ-fg/inst/hooks/local/hooks-config-to-inst.R': No such file or directory
```
Locally, I managed to get the hook to pass with `pre-commit run --all-files`.

**Comment by asottile** [comment]
hmmm I might've broken this recently -- what version of pre-commit do you have locally?

**Comment by lorenzwalthert** [comment]
pre-commit 2.20.0

**Comment by asottile** [comment]
ah I bet I broke this in pre-commit 3.0, I did have to change some stuff around with how `R` worked and I might've overlooked something :(

**Comment by lorenzwalthert** [comment]
No problem.  How can I help you fix it?

**Comment by asottile** [comment]
I probably have enough information to fix this -- can you open an issue on pre-commit/pre-commit?

**Comment by lorenzwalthert** [comment]
With pre-commit `3.0.1`, I get all hooks passing locally too. So I am not sure what issue description you expect if I open one in pre-commit/pre-commit?

**Comment by asottile** [comment]
hmmmm they seem to be failing for me! but I know how to fix it:

```
$ pre-commit  run --all-files
[INFO] Initializing environment for local:magrittr,purrr,rlang,yaml.
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Ordered regex pattern for spell-check exclusion..........................Failed
- hook id: spell-check-ordered-exclude
- exit code: 2

Fatal error: cannot open file '/home/asottile/.cache/pre-commit/repo6mrxh59i/inst/hooks/local/spell-check-ordered-exclude.R': No such file or directory

```

**Comment by asottile** [comment]
https://github.com/pre-commit/pre-commit/pull/2728 should fix it either way -- so I don't need the issue

**Comment by lorenzwalthert** [comment]
Ah now it also fails for me, must have had wrong executable or repo 🙃.

**Comment by asottile** [comment]
pre-commit 3.0.2 is out now and pre-commit.ci is updated to have that too -- thanks again for the report!

**Comment by lorenzwalthert** [comment]
Can confirm that it works now, thanks for releasing the fix near-immediately. 👍
