### ISSUE TITLE
Support dansabel

### ISSUE THREAD

**Issue by tykling** [pre-commit-ci/issues#167]
Hello :)

We use https://github.com/semaphor-dk/dansabel but it doesn't work on pre-commit.ci - it fails with the following error:
`build of https://github.com/semaphor-dk/dansabel@0ce89b6009f628b1681a825519b683dc0f1a1392 for python@python3 exceeds tier max size 250MiB: 384.1MiB`

Is this something I need to bring up with the authors of dansabel or is this an issue that needs to be fixed here? thanks! :)

**Comment by asottile** [comment]
`dansabel` pulls in `ansible` (which is the *entire* collection of ansible tooling) -- it probably wants `ansible-core`

```console
$ du -hs v*
59M	venvnew
424M	venvold
```

**Comment by tykling** [comment]
ah great :+1: I will speak to them, thank you! :)
