### ISSUE TITLE
pre-commit ci lite not working on private repos

### ISSUE THREAD

**Issue by adamchainz** [pre-commit-ci/issues#168]
Trying to install pre-commit ci lite on a private repo for a client and it isn't working

Tested with my own repo - when public, the fix commit was pushed back, but a second run whilst private didn't receive the fix. PR: https://github.com/adamchainz/example-pre-commit-ci-lite/pull/1

Appreciate you released 1.0.1 yesterday, so maybe it's still being worked on?

**Comment by asottile** [comment]
yeah I have not finished the pro version for pre-commit.ci lite -- I should probably finish that up

**Comment by asottile** [comment]
alright the code is all in place for this... all that's left is for it to get a little bit more popular?

> ❌ 100 app installations required (Current app installation count:61)

**Comment by asottile** [comment]
@adamchainz a pre-commit.ci classic subscription now grants access to lite for private repos as well -- so you should be able to try it again now?

**Comment by adamchainz** [comment]
Will try again next week when working with aforementioned client.

**Comment by asottile** [comment]
I have applied for marketplace inclusion today now that it has reached 100 users -- fingers crossed!

**Comment by asottile** [comment]
_**FINALLY**_ github approved it today https://github.com/marketplace/pre-commit-ci-lite
