### ISSUE TITLE
can't install posix collection

### ISSUE THREAD

**Issue by dallemon** [pre-commit-ci/issues#169]
i'm having issues installing the ansible.posix collection via requirements.yml
collections_paths is set to ./ in ansible.cfg under defaults

i receive the following error
´´´
Ansible-lint.............................................................Failed
- hook id: ansible-lint
- exit code: 1

WARNING  Ignore loading rule from /pc/clone/_8QQWgBeSLGqU-1h4Is86g/py_env-python3/lib/python3.11/site-packages/ansiblelint/rules/galaxy.py due to No module named 'pytest'
INFO     Running ansible-galaxy collection install -v -r requirements.yml -p /tmp/cache/ansible-compat/5694d0/collections
WARNING  Retrying execution failure 1 of: ansible-galaxy collection install -v -r requirements.yml -p /tmp/cache/ansible-compat/5694d0/collections
ERROR    Using /code/ansible.cfg as config file
Starting galaxy collection install process
Process install dependency map

ERROR    [WARNING]: The specified collections path '/tmp/cache/ansible-
compat/5694d0/collections' is not part of the configured Ansible collections
paths '/code'. The installed collection will not be picked up in an Ansible
run, unless within a playbook-adjacent collections directory.
[WARNING]: Skipping Galaxy server https://galaxy.ansible.com. Got an unexpected
error when getting available versions of collection ansible.posix: Unknown
error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/':
<urlopen error [Errno -3] Temporary failure in name resolution>
ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/': <urlopen error [Errno -3] Temporary failure in name resolution>

Got 1 exit code while running: ansible-galaxy collection install -v -r requirements.yml -p /tmp/cache/ansible-compat/5694d0/collections
´´´

**Comment by asottile** [comment]
network is not allowed at runtime -- there are a few duplicates -- please search around next time!  at least for ansible I know some are using submodules instead or `additional_dependencies` to bring in other modules

**Comment by dallemon** [comment]
thanks, i did do a search, but obviously not good enough.
i'll have a look at your suggestions.
