### ISSUE TITLE
support for check-manifest

### ISSUE THREAD

**Issue by henryiii** [pre-commit-ci/issues#17]
Currently, check-manifest does not work, because it tries to build the SDist for a package to compare, and pyproject.toml PEP 518 dependencies can't download. See builds here. https://github.com/scikit-hep/particle/pull/278

I hope I can avoid this by making this a "manual" hook (which I do in larger projects anyway, because it's slow), but it is a noticeable issue.

**Comment by asottile** [comment]
I fixed `check-manifest` to not reach out to the internet always -- check out [their README](https://github.com/mgedmin/check-manifest#version-control-integration) (the second example)

**Comment by henryiii** [comment]
Great! :tada:
