### ISSUE TITLE
Support GitHub merge queues

### ISSUE THREAD

**Issue by pokey** [pre-commit-ci/issues#170]
GitHub has a feature in public beta called [merge queues](https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/).  In order for a PR to advance, checks must be triggered for PRs in the merge queue.  These checks don't seem to be triggering for pre-commit CI.

See [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-other-ci-providers) for possibly helpful information

**Comment by asottile** [comment]
this should be pretty easy -- unfortunately it'll request a new permission from every app 🙃 

I'll set it up as a read-only check -- will need to play around with the check name since I assume it has to match the one from the pull request and branch protection (even though it's not a `pr` run)

**Comment by pokey** [comment]
Yes I think life will be much easier all around if it's just the same name. Probably not too unjustified, as although it's not triggered by the PR trigger, it's still running for a PR 🤷‍♂️

**Comment by asottile** [comment]
alrighty -- this should be live!

**Comment by pokey** [comment]
awesome thanks!
