### ISSUE TITLE
lite-action does not push to pull request

### ISSUE THREAD

**Issue by egeakman** [pre-commit-ci/issues#172]
I'm attempting to configure pre-commit CI Lite on my public repository. When pre-commit-ci/lite-action@v1.0.1 is run, I receive the following output:

```
fetching pr...
saving artifact...
artifact published!
```

However, I noticed that no commit is being pushed. It's possible that the issue lies in the fact that the workflow file is not yet available in the default branch.

In case you need to review the situation, here is the link to the pull request: https://github.com/python/python-docs-tr/pull/120

Please let me know if there are any ways to improve the setup to ensure that the commits get pushed. Thank you.

**Comment by asottile** [comment]
there's a bit in the docs that I think you've missed:

> note: the step must have either the default name or contain the text pre-commit-ci-lite. the application uses this to find the right workflow.

**Comment by egeakman** [comment]
>there's a bit in the docs that I think you've missed:

Oh. Well, thank you. I guess I should get better sleep to be able to pay more attention.
