### ISSUE TITLE
Rust based hooks with foreign repos fail.

### ISSUE THREAD

**Issue by Swiftb0y** [pre-commit-ci/issues#173]
While trying to evaluate pre-commit CI, I encountered an issue with Rust and hooks that don't use `repo: local`. 

The error is basically the same as in #121 but in this case it wouldn't really make sense to use `repo: local` as a workaround. 

This PR demos the problem: https://github.com/Swiftb0y/pre-commit.ci-evaluation/pull/2
This is the corresponding pre-commit.ci run: https://results.pre-commit.ci/run/github/607242900/1677514766.DnAk-Np0RdaiZRFwB1axrg

**Comment by asottile** [comment]
iirc if you need a specific `rustc` you need to also specify `language_version`

**Comment by Swiftb0y** [comment]
[Removing all version specifications](https://github.com/Swiftb0y/pre-commit.ci-evaluation/pull/2/commits/d55568abe22d4da214437d0dd548741f074eea12) works, but [specifying `language_version` explicitly](https://github.com/Swiftb0y/pre-commit.ci-evaluation/pull/2/commits/b2fb2f029560c07723d0346b91d529e8f5c67b3b) doesn't work unfortunately.

**Comment by asottile** [comment]
hmmm that probably points at a `pre-commit` issue itself -- when it sets up a custom `rustup` toolchain it should override `RUSTUP_HOME` while installing: https://github.com/pre-commit/pre-commit/blob/294590fd124484a786ba90423fa5d89536a6de98/pre_commit/languages/rust.py#L153-L156

**Comment by Swiftb0y** [comment]
Makes sense. What are the next steps now? Fixing the problem in pre-commit? I'm afraid I'm personally not comfortable enough with python to fix this myself.

**Comment by asottile** [comment]
yeah there'll need to be some fix in pre-commit

**Comment by asottile** [comment]
should be fixed now

**Comment by Swiftb0y** [comment]
Thank you for the quick fix. Do you know when pre-commit.ci will get updated to the new pre-commit version?

**Comment by asottile** [comment]
it already has

**Comment by Swiftb0y** [comment]
Ah yes thank you very much. I figured something was wrong because my test run was queued for 35 minutes but it passed now.

**Comment by asottile** [comment]
yeah github packages is/was down -- #174
