### ISSUE TITLE
github packages outage - 2023-03-01

### ISSUE THREAD

**Issue by pmav99** [pre-commit-ci/issues#174]
My job has been queued for ~20 minutes now. I guess this means that either pre-commit.ci has many new users, which is great, or that some system is down. If time permits, adding a status page to pre-commit.ci providing some more info would be really nice.

**Comment by sanders41** [comment]
I just experienced something similar and the job ended with an error:

```console
Error: statfs /home/pcworker/.cache/pre-commit-ci/lang/d5eea090d4b2d21db761e0c7cd77a1d5800d6b60d45c017d45256c8517428255/lua: no such file or directory
```

pre-commit passes locally so I don't think it is related to a code issue.

**Comment by asottile** [comment]
github packages is having an outage right now: https://www.githubstatus.com/

there's not too much that we can do during this

**Comment by asottile** [comment]
@sanders41 can you link your run? I'm not 100% certain that one is related

the queue has been re-processed so any stuck runs should now be completed.  I'm continuing to watch github's progress

**Comment by sanders41** [comment]
Here you go: https://results.pre-commit.ci/run/github/437570125/1677678017.8AVpGMzvTNOG2xxuddHOmA

**Comment by asottile** [comment]
@sanders41 very strange -- looking at the logs for it github handed us an empty blob somehow (?) -- I'll put some additional checking in place for that moving forward.  new runs should succeed for now though but I don't have an easy way to rerun that failed one

**Comment by sanders41** [comment]
Thanks for looking into it. No worries on the rerun, since it passes locally I know I'm good to merge.

**Comment by asottile** [comment]
marking this as resolved
