### ISSUE TITLE
How to wait for pre-commit to complete before running other workflows/jobs

### ISSUE THREAD

**Issue by Crocmagnon** [pre-commit-ci/issues#175]
This is more a question than an issue: how can I wait on pre-commit.ci to finish its job before triggering/continuing another workflow?

Context: I'm often working alone on my side projects and I want to trigger a deployment to production whenever there's a push on the master branch. However, I don't want to deploy code that doesn't pass pre-commit hooks.

I'm currently running pre-commit directly as part of my own workflow but it feels very inefficient since pre-commit.ci is way faster.

**Comment by asottile** [comment]
I believe #106 contains the previous discussion about this

**Comment by Crocmagnon** [comment]
Thanks, I didn't find it while searching. I'll have to check whether that fits my use case though.
