### ISSUE TITLE
Incorrect update

### ISSUE THREAD

**Issue by Freed-Wu** [pre-commit-ci/issues#176]
![screen-2023-03-28-09-35-22](https://user-images.githubusercontent.com/32936898/228104302-6b437dcb-a371-4b31-95b3-0fc09913e4e4.jpg)

vint will be **degraded** from 0.4a4 to 0.4a3. Is it a bug? Because 0.4a4 is greater than 0.4a3.

**Comment by asottile** [comment]
the latest tag on the primary branch is a3 so this is correct

**Comment by Freed-Wu** [comment]
<https://github.com/Vimjas/vint/tags> the latest tag is 0.4a4 <https://github.com/Vimjas/vint/releases/tag/v0.4a4>.

**Comment by asottile** [comment]
read my message carefully
