### ISSUE TITLE
question about pre-commit ci and updating hooks

### ISSUE THREAD

**Issue by lwasser** [pre-commit-ci/issues#177]
Hi!
I noticed that pre-commit ci is not updating hook as i would expect it to
An example config file is here:
https://github.com/pyOpenSci/python-package-guide/blob/main/.pre-commit-config.yaml

do i need to do something special to get it to update hooks? i just changed the frequency to monthly but i've had it running for a while and it never submits a pr to update things. Many thanks!

**Comment by asottile** [comment]
you had previously set `quarterly` which will be updated the first week of the first month of each quarter.  you've only just changed it to monthly which will be updated the first week of the month (which has not happened yet)
