### ISSUE TITLE
pre-commit ci action lite merging a PR from a fork

### ISSUE THREAD

**Issue by itsarune** [pre-commit-ci/issues#179]
Hello, our developers write code in their own forks of our public repo and then merge pull requests to our master branch by merging across forks. This is [an example](https://github.com/UBC-Thunderbots/Software/pull/2886) of such a PR. I installed the "pre-commit ci lite" action for the repo. I am using a custom formatting fix script that we defined a hook for in `.pre-commit-config.yaml`. I am able to trigger this formatting script and obtain a diff from pre-commit. I also see the following messages in pre-commit-ci-lite:
```
fetching pr...
saving artifact...
artifact published!
```
However, we don't see any commit pushed to fix the changes made by our fix formatting script. I only see a message that says: "pre-commit.ci lite Pending — running" in the status checks at the bottom of the PR.

Would pre-commit work in this situation where the base of the pull request is a fork of the repo?

**Comment by asottile** [comment]
weird -- can you try rerunning the action?  the error on pre-commit ci's side is:
```
[ERROR] AssertionError: no artifact? repo_id=141040516 run_id=4684507328
```

**Comment by itsarune** [comment]
I reran the action and looks like the same thing is happening

**Comment by asottile** [comment]
very strange -- this is working elsewhere so there's something special about this case.  for some reason pre-commit ci can't even read the github actions artifacts for that PR

**Comment by itsarune** [comment]
we fixed this by running pre-commit in a separate workflow file as per @asottile's suggestion and now works. should this issue be closed?

**Comment by asottile** [comment]
I think I need to document that still -- or figure out some way to not need the full workflow to complete
