### ISSUE TITLE
pre-commit-ci and autofix_prs set to false

### ISSUE THREAD

**Issue by djgoku** [pre-commit-ci/issues#182]
I have `autofix_prs: false` [1], but PRs are still being opened. Is this the intended behavior?

[1] https://github.com/djgoku/dot-files/blob/main/.pre-commit-config.yaml#L7

**Comment by asottile** [comment]
you are confusing autofix and autoupdate -- the latter is not allowed to be disabled -- there are a few duplicates in the issue tracker which address the reasonings there -- I'd recommend searching those!
