### ISSUE TITLE
pre-commit ci failing to clone 

### ISSUE THREAD

**Issue by chai-unitary** [pre-commit-ci/issues#183]
We have configured pre-commit ci to run on PRs made to our private-repo since few weeks. It worked fine until yesterday.

Since yesterday, pre-commit ci job is failing during the clone stage with following message on GH action
```
Error during clone
```
<img width="854" alt="Screenshot 2023-06-08 at 08 52 10" src="https://github.com/pre-commit-ci/issues/assets/130452569/2f0f3d4e-105a-4661-a825-e9bb8e7fdabe">

Details reveal that pre-commit ci job is timing out 
```
fetch attempt 1...
    => timeout after 30s
fetch attempt 2...
    => timeout after 30s
fetch attempt 3...
    => timeout after 30s
```

**Comment by asottile** [comment]
how large is your repository? was this perhaps during github's outage yesterday?

**Comment by chai-unitary** [comment]
not super large. how do you quantify size though?

not related to yesterday's outage as its failing even now

**Comment by asottile** [comment]
can you provide a link to the run (the runs are private for private repos) -- I can debug a little bit from that but might need some additional information

**Comment by chai-unitary** [comment]
https://results.pre-commit.ci/run/github/191402629/1686156604.VNc1vTztSpaG01KybqyxiQ
https://results.pre-commit.ci/run/github/191402629/1686150689.sepc5hScTbu0Ay-4yXhsmg

**Comment by asottile** [comment]
hmmm looking at historical runs I see a slow uptick in clone time -- and some where individual tries timed out

how large is the repo? (or maybe it has lots of files?)

**Comment by chai-unitary** [comment]
Size of git repository
```
 du -sh .git/
1.1G    .git/
```

Number of lines in repo
```
git ls-files | xargs cat | wc -l
4238757
```

Number of files
```
 git ls-files | wc -l
    2123
```
Are there limits on the size & is that causing time out?

**Comment by asottile** [comment]
the limit is just on time -- 30 seconds to make a clone.  1G is probably pretty close to taking 30 seconds.

would you like me to take a peek at the repo and see if there's anything glaringly obvious that may help with the performance?

**Comment by chai-unitary** [comment]
Thanks for the prompt response. We will try and address the 1G size issue and get back in case we still have difficulties. Closing this topic as the root-cause [size>1G] seems to be identified
