### ISSUE TITLE
CI doesn't run weekly autoupdate

### ISSUE THREAD

**Issue by chemelli74** [pre-commit-ci/issues#188]
I added the CI config to `.pre-commit-config.yaml` as descried in the documentation but the task doesn't run.

Here the config details: https://github.com/chemelli74/aiovodafone/blob/main/.pre-commit-config.yaml#L6-L9

Simone

**Comment by asottile** [comment]
it doesn't look like you've installed the CI application -- https://pre-commit.ci

**Comment by chemelli74** [comment]
If I'm not wrong, I installed it but it didn't run this afternoon as expected :-(

Can you be so kind to tell me what's wrong on my setup please ?
Thank you in advance,

Simone

**Comment by asottile** [comment]
please be patient.  there are thousands of repositories

**Comment by chemelli74** [comment]
> please be patient. there are thousands of repositories

Oh no hurry, just wanted to understand if the "usually run at 4PM on Monday" is still applicable.

Simone

**Comment by asottile** [comment]
that is when it starts yes.  please stop sending a signature this is not email
