### ISSUE TITLE
badge / latest link do not handle default branch names with slashes in them

### ISSUE THREAD

**Issue by bastienboutonnet** [pre-commit-ci/issues#19]
Both in the pre-commit ci web app and in my readme it seems like the badge is not resolving or so

<img width="651" alt="Screenshot 2020-11-14 at 13 40 58" src="https://user-images.githubusercontent.com/4304794/99147195-4b3e2c80-267f-11eb-956b-d7484e440a13.png">

and https://github.com/bastienboutonnet/sheetwork/blob/chore/add_precommit_ci_badge/README.md

Not sure if it's a me issue but thought I'd post it here.

**Comment by asottile** [comment]
oops looks like this is a microbug in the web routes -- your default branch contains a slash and so it's not matching the url segment

your code is correct, you should be able to leave it and I'll adjust the routing bits

**Comment by asottile** [comment]
should be fixed now -- thanks for the report!

```markdown
[![pre-commit.ci status](https://results.pre-commit.ci/badge/github/bastienboutonnet/sheetwork/dev/nicolas_jaar.svg)](https://results.pre-commit.ci/latest/github/bastienboutonnet/sheetwork/dev/nicolas_jaar)
```

[![pre-commit.ci status](https://results.pre-commit.ci/badge/github/bastienboutonnet/sheetwork/dev/nicolas_jaar.svg)](https://results.pre-commit.ci/latest/github/bastienboutonnet/sheetwork/dev/nicolas_jaar)

**Comment by asottile** [comment]
(note that I didn't change the markdown, I just put it in the comment so it was clear what I was rendering below)

**Comment by bastienboutonnet** [comment]
Awesome! It works indeed :) Thanks for looking into it @asottile
