### ISSUE TITLE
`pre-commit.ci` website is down

### ISSUE THREAD

**Issue by mathbunnyru** [pre-commit-ci/issues#192]
It seems that the CI website is currently down.
I think it's not just for me: https://www.isitdownrightnow.com/pre-commit.ci.html

**Comment by asottile** [comment]
it's weird because it's resolving for me and for github but not for people in the EU

I suspect some sort of cloudflare weirdness

**Comment by mathbunnyru** [comment]
It works for me now. I will close the issue.
