### ISSUE TITLE
Clarify if all files run in CI

### ISSUE THREAD

**Issue by tofu-rocketry** [pre-commit-ci/issues#194]
Could you note in the documentation if the CI checks run on all files or just changed ones please?

The `run` section of the CI doesn't show what command is being run to invoke the checks and I've not found anything definitive elsewhere.

**Comment by asottile** [comment]
it's `pre-commit run --all-files` -- don't think this really needs documenting because it can't be anything else if it's a gating mechanism

**Comment by tofu-rocketry** [comment]
That's what I assumed, but wasn't completely certain. For Pull Requests, there are other tools that will only look at touched files, which usually provides sufficient gating, so I don't understand that point. Is it really not worth one line in the docs?

**Comment by asottile** [comment]
there are many things which fail without the file touched (check-symlinks, mypy, etc.)

**Comment by tofu-rocketry** [comment]
If you don't think it's worth being explicit, then that's up to you, but as a user, I like to be reassured of how services are actually working. What's obvious to you isn't going to be obvious to all your users.
