### ISSUE TITLE
Empty resolv.conf, Go app name resolution issues

### ISSUE THREAD

**Issue by scop** [pre-commit-ci/issues#196]
pre-commit.ci runners seem to be running with an empty /etc/resolv.conf.

I suspect because of this, name resolution does not work at least with some Go apps built outside of pre-commit.ci, as they fall back to attempting to resolve through `::1` port 53. I guess adding some valid nameservers to /etc/resolv.conf would fix this.

Example run: https://results.pre-commit.ci/run/github/262338484/1699897606.Epog7DLfQ9eabunHDgTMug
> `dial tcp: lookup github.com on [::1]:53: read udp [::1]:35521->[::1]:53: read: connection refused`

**Comment by asottile** [comment]
network is not allowed at runtime
