### ISSUE TITLE
fix building of nodejs-based hooks

### ISSUE THREAD

**Issue by asottile** [pre-commit-ci/issues#2]
For example: https://results.pre-commit.ci/run/github/261542529/1603753977.V8WMCZpnSTavW3yTrUdQhA

```
build attempt 1...
    => error
    [INFO] Installing environment for https://github.com/prettier/prettier.
    [INFO] Once installed this environment will be reused.
    [INFO] This may take a few minutes...
    An unexpected error has occurred: CalledProcessError: command: ('/pc/clone/uXI4ri67TKuUOEqHk8jLiQ/node_env-default/bin/node', '/pc/clone/uXI4ri67TKuUOEqHk8jLiQ/node_env-default/bin/npm', 'install')
    return code: 1
    expected return code: 0
    stdout: (none)
    stderr:
        npm ERR! code EROFS
        npm ERR! syscall mkdir
        npm ERR! path /src/.npm
        npm ERR! errno EROFS
        npm ERR! rofs Invalid response body while trying to fetch https://registry.npmjs.org/@angular%2fcompiler: EROFS: read-only file system, mkdir '/src/.npm'
        npm ERR! rofs Often virtualized file systems, or other file systems
        npm ERR! rofs that don't support symlinks, give this error.
    
    Check the log at /pc/pre-commit.log
```

**Comment by asottile** [comment]
the issue is `npm install -g .` causes `npm` to symlink outside of the environment directory (which then doesn't end up in the environment artifact)

I'll probably need to improve pre-commit to handle this better

**Comment by asottile** [comment]
*some* nodejs hooks work now (I've added nodejs to the image) but still have the problem with symlinks to nodejs source directories

**Comment by asottile** [comment]
note that if you're using prettier, you can work around this by using prettier/pre-commit instead of prettier/prettier

**Comment by asottile** [comment]
this should be fixed now!  https://results.pre-commit.ci/run/github/261542529/1603953407.q29VL40mRmu8rE5kiTHaFA

**Comment by hugovk** [comment]
Confirmed, thank you!

https://github.com/hugovk/pypistats/pull/183
