### ISSUE TITLE
Prettier error message - pre-commit.ci only

### ISSUE THREAD

**Issue by csabasari** [pre-commit-ci/issues#200]
Good evening,

We got a strange issue when the pre-commit.ci runs. Reference run [linked here](https://results.pre-commit.ci/run/github/726092803/1703092893.RPJFdYrvTu-Ubg7a732uoQ). Locally it runs well, however we are using some help with: `export PRETTIER_LEGACY_CLI=1` . 

```
prettier.................................................................Failed
- hook id: prettier
- exit code: 1

?25h?25h
```
I was try to check documentation if there is possibility to submit ENV variables during the run, but I haven't found anything related. Also checked documentation (keyword was ENV/env - 58 match, none of them relevant) and issues on pre-commit repository, but no resolution. Also checked prettier on GitHub, found this one: https://github.com/prettier/prettier/issues/15832 . 

Should we wait for them to fix it, or is there a way to inject this ENV variable somehow? Thank you in advance!

**Comment by asottile** [comment]
dupe https://github.com/pre-commit/pre-commit/issues/2367#issuecomment-1114126040
