### ISSUE TITLE
Any chance to sign pre-commit.ci up as a CircleCI user?

### ISSUE THREAD

**Issue by larsoner** [pre-commit-ci/issues#201]
In our org we prevent unregistered users from spending our CircleCI credits. But it leads to this [block-unregistered-user](https://support.circleci.com/hc/en-us/articles/17441333580827-Why-do-I-see-a-block-unregistered-user-error-in-my-build-) any time `pre-commit.ci` pushes a commit to one of our PRs ([here](https://app.circleci.com/pipelines/github/mne-tools/mne-python/22451/workflows/010b3f0a-e1fc-4055-b627-ed95350d226c/jobs/62702) is an example from autofix.ci but the problem is the same).

Would it be possible to sign the pre-commit.ci bot/email up for CircleCI so that this stops happening? In theory it's free to sign up.

I could un-block unregistered users but that carries risks. And there is no way I know of to add unregistered users to an allowlist on CircleCI.

**Comment by larsoner** [comment]
... the reply from the autofix.ci folks was that [they use a GitHub App bot so there is nothing they can do](https://github.com/autofix-ci/action/issues/11) -- if that's indeed the case for pre-commit-ci, feel free to close!

**Comment by asottile** [comment]
yep just an app here

I would recommend asking circle CI to add allowances for github bots
