### ISSUE TITLE
Disable individual repos

### ISSUE THREAD

**Issue by ms32035** [pre-commit-ci/issues#203]
Please add an option to disable individual repos at https://results.pre-commit.ci/ 
We enable the app for all repos (including the new ones), but some of them don't have pre-commit-config.yaml, and these are left in hanging state. Issue is rather urgent and blocking

**Comment by asottile** [comment]
I have no control over that unfortunately.  that's github's ui

**Comment by ms32035** [comment]
That's not github UI, but your bespoke

**Comment by asottile** [comment]
you selected the "all repos" on github's ui, I have no control over that

**Comment by ms32035** [comment]
This I understand, but since you also have your UI, that's a perfect place to add disabling of individual repos. Other solution would be to finish the job succesfully if no pre-commit-config is found, or make such behaviour configurable. If 90% of your repos use pre-commit, and most new ones too, you wouldn't like to manually click for every single one of them

**Comment by asottile** [comment]
while it is the perfect place, github does not provide an API to do so

and I pay for every request so it does not incentivize me to perform runs for waste so that's why they fail
