### ISSUE TITLE
"pre-commit.ci lite was unable to push to the branch -- branch missing?" Error

### ISSUE THREAD

**Issue by lucasssvaz** [pre-commit-ci/issues#205]
While configuring pre-commit.ci lite for our repo it suddenly started failing with the error "pre-commit.ci lite was unable to push to the branch -- branch missing?" as seen in this PR:

https://github.com/espressif/arduino-esp32/pull/9132

I don't know if I messed something up or there's something wrong in the backend. (Btw, this error message is not very useful by itself. Would it be possible to make the error more specific or provide a log?)

**Comment by asottile** [comment]
unfortunately there's no more additional information.  I don't actually know why github rejected the push (usually it means the app got revoked or the branch was deleted or there's a conflict)

**Comment by lucasssvaz** [comment]
The app permissions are ok and the branch still exist. What kind of conflict could be happening ?

**Comment by asottile** [comment]
for instance if the auto fixes conflict with the main branch's progression

**Comment by lucasssvaz** [comment]
Just tried and it isn't. It works correctly in my own for but not when I add it to our organization (as an admin). The same PR:

https://github.com/espressif/arduino-esp32/pull/9132
https://github.com/lucasssvaz/arduino-esp32/pull/4

Do you have any idea what could cause this ? I already checked the things you mentioned and they all seem OK. Is there any special config or permissions required for organization repos ?

**Comment by asottile** [comment]
ah yes this problem.  PRs from an organization to an external repo cannot be pushed at all.  this is just an annoying github limitation.  it's recommend sending in a support issue to github itself such that they know more people want this

**Comment by lucasssvaz** [comment]
Is this a limitation in the non-lite version as well ? (I guess it is as this is github related)

**Comment by asottile** [comment]
yep, there's a special error message in the full version for this case, I can probably add it to lite as well

**Comment by lucasssvaz** [comment]
I would be very useful for future users, thank you!

**Comment by lucasssvaz** [comment]
Found out the problem. It was the hooks editing the `.github` folder, which they don't have permissions. Once I added it to the exclusions list, it worked as expected.

**Comment by asottile** [comment]
I've added more specific error messages based on the push output -- hopefully that'll make this less confusing next time (there's also a special message for workflows being modified as well!)

**Comment by lucasssvaz** [comment]
Thanks a lot!
