### ISSUE TITLE
Configuration Request - only run on files changed in PR

### ISSUE THREAD

**Issue by rgasper** [pre-commit-ci/issues#206]
I'd love to use pre-commit.ci for my organization, but we have lots of old files from before we regularly used pre-commit that do not pass the formatters/linters. This is not an in issue in the regular local workflow, since pre-commit only runs on the files affected by a commit by default.

We'd like to be able to configure pre-commit.ci to run not on all files in the repository, but just the ones affected by the commits in the PR. We unfortunately can't effectively use pre-commit.ci w/o this change.

**Comment by asottile** [comment]
there's quite a few duplicates including at least #90 from a quick search and https://github.com/readme/guides/code-review

**Comment by rgasper** [comment]
@asottile while I do understand your reasoning in #90 , I disagree that it's always the right path. My organization has tens if not hundreds of thousands of lines of code that were not originally committed with linting and formatting, and all that code has been functioning as designed for years at this point w/ no modification. There's little reason IMO to spend days going through it all just to make the ci tool happy, certainly not enough value delivered to substantiate the effort over building new stuff, when we get a lot of value out of pre-commit via the local git hooks already.

Anyway if you don't think it's worth the effort to build this feature that's of course your call. Thanks for your work on pre-commit, it's an excellent tool

**Comment by asottile** [comment]
> changed-files-only may be a paid feature in the future but I have no plans to implement it right now

in the duplicate I stated I'm open to implementing it eventually -- but it will likely be a paid only feature
