### ISSUE TITLE
feature request: configurable PR reviewers

### ISSUE THREAD

**Issue by rkm** [pre-commit-ci/issues#214]
E.g., Dependabot has [this](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#reviewers)

**Comment by asottile** [comment]
this is easier to do with github actions rather than pre-commit.ci needing to handle this -- something similar to this? https://github.com/pre-commit-ci/issues/issues/24#issuecomment-732315853

**Comment by asottile** [comment]
actually -- an even easier way to accomplish this would be to use CODEOWNERS for `.pre-commit-config.yaml` -- then github will always assign the right people (since it's always going to edit that file!)

**Comment by asottile** [comment]
going to recommend that as the "official" solution unless there's a good reason not to ^

**Comment by rkm** [comment]
Thanks! I'll give that a try
