### ISSUE TITLE
pre-commit autoupdate not running on forked repo

### ISSUE THREAD

**Issue by injust** [pre-commit-ci/issues#215]
I have a public, forked repo with pre-commit.ci enabled, but the weekly autoupdate isn't running.

Its `.pre-commit-config.yaml` is identical to two of my other public repos, and autoupdate _is_ running on those. The only difference I can think of is that this repo is forked.

Is there something special about forked repos that causes the autoupdate to not run?

**Comment by asottile** [comment]
public forks do not receive auto updates at all

**Comment by injust** [comment]
That's what I suspected, thanks for confirming.

Maybe worthwhile to add a blurb about that somewhere?

**Comment by asottile** [comment]
yeah I kept it a bit secret because it was discovered as an abuse vector (users were signing up with thousands and thousands of forks and ruining the fun for everyone else)

**Comment by asottile** [comment]
fwiw paid plans have fork support for autoupdate, but it's probably not worth a paid plan for just that
