### ISSUE TITLE
Restart the PR check

### ISSUE THREAD

**Issue by wawrzek** [pre-commit-ci/issues#217]
The pre-commit.ci checked failed. It was because of rust not being served by default. I adjust the configuration (I hope that adding language: rust will fix it), but I see no way to resubmit/restart the PR check.

**Comment by asottile** [comment]
you can read the docs at https://pre-commit.ci which tell you how to rerun a pr check

**Comment by wawrzek** [comment]
@asottile it could be more visible. If anyone finds this question, the answer is:
> you can trigger a re-run on a pull request by commenting pre-commit.ci run (must appear on a line by itself). alternatively, one can attach a pre-commit.ci run label to the pull request.

I used the `pre-commit.ci run` label and it worked.

**Comment by asottile** [comment]
no it couldn't, you didn't read the docs in the first place
