### ISSUE TITLE
Difference in behavior with local run for flake8 noqa comments

### ISSUE THREAD

**Issue by matthewfeickert** [pre-commit-ci/issues#22]
Hi. Thanks for making pre-commit.ci :+1: I have a run on https://github.com/pyhf/pyhf-validation/pull/18 that [is failing](https://results.pre-commit.ci/run/github/244832903/1605644605._k9gzF10ScuvMhZqY98Mfg) with

```
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

scripts/validate_systs.py:207:1: C901 'outlier_plot' is too complex (21)
```

though this is strange as the in-line ignore for this was placed at line 172

```
$ sed -n "172p" scripts/validate_systs.py 
@click.command()  # noqa: C901
```

to avoid the warning when running `pre-commit` over the whole codebase

```
$ cat .pre-commit-config.yaml 
repos:
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.7.4
    hooks:
    - id: pyupgrade
      args: ["--py36-plus"]
$ pre-commit run --all-files
black....................................................................Passed
flake8...................................................................Passed
pyupgrade................................................................Passed
```

My expectation would be that running `pre-commit run --all-files` would give me the same behavior as `pre-commit.ci`. So I'm not sure if this difference in behavior is a bug or if there are additional flags being used by `pre-commit.ci` that I'm unaware of.

Please let me know if there is additional information that I can provide that would be helpful, or any tests that I can perform.

cc @kratsg @lukasheinrich

**Comment by asottile** [comment]
while I look into this, if you want you can try out exactly what pre-commit.ci runs by using the public image: https://github.com/orgs/pre-commit-ci/packages/container/package/runner-image

**Comment by asottile** [comment]
for what it's worth, I get what pre-commit.ci gets locally:

```
$ pre-commit  run --all-files
black....................................................................Passed
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

scripts/validate_systs.py:207:1: C901 'outlier_plot' is too complex (21)

pyupgrade................................................................Passed
```

**Comment by asottile** [comment]
ah yeah I know what this is, the python ast changed the node offset of functions between 3.7 and 3.8 -- it used to be on the decorator and now it's on the function:

```yaml
repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
      name: flake8 (py38)
    - id: flake8
      name: flake8 (py37)
      language_version: python3.7
    - id: flake8
      name: flake8 (py36)
      language_version: python3.6
```

```console
$ pre-commit  run --all-files
flake8 (py38)............................................................Failed
- hook id: flake8
- exit code: 1

scripts/validate_systs.py:207:1: C901 'outlier_plot' is too complex (21)

flake8 (py37)............................................................Passed
flake8 (py36)............................................................Passed
```

if you want my 2c, I think C901 is not a useful linting error -- sometimes functions need to have lots of branches and splitting them up makes the code worse (and most developers will respond by `noqa` and/or adjusting `max-complexity` anyway).  Personally I'd recommend removing `max-complexity` from your flake8 configuration which will turn off `C901` entirely

**Comment by matthewfeickert** [comment]
> for what it's worth, I get what pre-commit.ci gets locally:

Huh. Interesting given

```
(pyhf-validation-dev) $ pre-commit clean
Cleaned /home/feickert/.cache/pre-commit.
(pyhf-validation-dev) $ pre-commit run --all-files
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8.
[INFO] Initializing environment for https://github.com/asottile/pyupgrade.
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://gitlab.com/pycqa/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/asottile/pyupgrade.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
black....................................................................Passed
flake8...................................................................Passed
pyupgrade................................................................Passed
```

Though if you can reproduce what pre-commit.ci is getting on your Linux VM then that means that there's something on my end that I'll need to figure out. I'll close this Issue now. Thanks!

**Comment by matthewfeickert** [comment]
> if you want my 2c, I think C901 is not a useful linting error -- sometimes functions need to have lots of branches and splitting them up makes the code worse (and most developers will respond by `noqa` and/or adjusting `max-complexity` anyway). Personally I'd recommend removing `max-complexity` from your flake8 configuration which will turn off `C901` entirely

Sounds good to me. Thanks for the lightning fast response and advice.

**Comment by asottile** [comment]
another flake8-specific tip -- I'd suggest `extend-ignore` over `ignore` as it'll preserve the existing default-ignored codes
