### ISSUE TITLE
timeout errors during mergeable check

### ISSUE THREAD

**Issue by chrishavlin** [pre-commit-ci/issues#220]
Hi there, 

I've got a number of repositories with pre-commit.ci hooks enabled and at least 2 of them are hanging then failing with timeout errors.

```
mergeable check:
timeout waiting for merge ref
```

here's one job for example:
https://results.pre-commit.ci/run/github/448138442/1719600805.uazrychWQ-CSLV9FF7lYgA 

anything I should try on my end?

**Comment by asottile** [comment]
> anything I should try on my end?

load up https://githubstatus.com :)

**Comment by chrishavlin** [comment]
hah, ok, that makes sense. my other tests somehow made it through the queue :) thanks!!

**Comment by ssbarnea** [comment]
Ended up with the same issue. I wonder if it would not worth including a link to to https://githubstatus.com/ directly into the timeout message. Sometimes we do not spot the glitch in the matrix so quickly, especially as github UI seems to be working just fine.

**Comment by asottile** [comment]
I mean, usually githubstatus isn't up to date either
