### ISSUE TITLE
Add `--repo` and `--freeze` flags to pre-commit.ci config

### ISSUE THREAD

**Issue by Peiffap** [pre-commit-ci/issues#221]
Thanks for making this tool!

I'd like to use pre-commit.ci autoupdating for my projects but would appreciate the ability to specify additional flags in the ci config.

  1. Expose the `--freeze` flag to store "frozen" hashes in `rev` instead of tag names.
  2. Expose the `--repo` flag so I can specify which repos to apply the autoupdate to. The use case for this is prettier being messed up for now, and me not wanting to have to edit all of the pull requests manually before accepting (and I'm confident I'm not alone in this).

**Comment by asottile** [comment]
the former already works, it's the same as pre-commit 

the latter will not be supported -- see #83

**Comment by Peiffap** [comment]
Thanks for getting to this so promptly!

Did I miss the part about `--freeze` somewhere in the documentation? It'd be nice to have it added there for completeness.

Fair enough about the `--repo` flag (though I feel compelled to point out, as others have in that thread, that I don't believe not offering the feature won't reduce your operating costs -- it'll just make users jump through (admittedly small, i.e. manually changing PRs) hoops to achieve their goal).

**Comment by asottile** [comment]
if you've run freeze once and committed it pre-commit ci will keep the revisions in the freeze format

**Comment by asottile** [comment]
there's nothing to document because it just works

**Comment by asottile** [comment]
> though I feel compelled to point out, as others have in that thread, that I don't believe not offering the feature won't reduce your operating costs

nobody asked for your opinion and you don't know how the costs work and you're not paying for it either so you're in no position to nag for features

**Comment by Peiffap** [comment]
I see. I'm not entirely convinced that's the most natural way for it to work, but if I'm the first person to ask I take it that's just me. Good to have it spelled out here in any case. Thanks.

As for the last comment, I believe you're perhaps projecting some hostility I didn't intend to convey. I'm not "nagging for features"; I'm pointing out a perceived inconsistency in your reasoning, which might well be due to a lack of understanding on my end of how costs work. You are, of course, free to disregard that!
I like the stuff you build and I want to be on your side, but belittling me and other people for suggesting things is pretty lame.

**Comment by asottile** [comment]
your message to me reads as "you don't know how your costs work and I think
I know better so you should do the thing I want despite you repeatedly
declining the feature"

I hope you can understand the inappropriateness of that and I encourage you
to do better in the future

**Comment by Peiffap** [comment]
I see. It's a misunderstanding, then; I wasn't trying to imply that "you don't know how your costs work" or that "I think I know better." In any case, you've made your position abundantly clear! Thanks for that.
