### ISSUE TITLE
Getting `Could not connect, are you offline?` when opening a PR

### ISSUE THREAD

**Issue by stefanofusai** [pre-commit-ci/issues#222]
As the title says, when I open a PR I get the following error:

<img width="1312" alt="image" src="https://github.com/pre-commit-ci/issues/assets/46556949/0d83c66f-2b2b-4f28-a1a6-0a08a23128e8">

The action is running on GitHub so I'm unsure what the problem could be. Another run had the same issue happen with [https://pypi.org/simple/django-import-export/](https://pypi.org/simple/django-import-export/) instead of [https://pypi.org/simple/gunicorn/](https://pypi.org/simple/gunicorn/)

<img width="1308" alt="image" src="https://github.com/pre-commit-ci/issues/assets/46556949/d05f3239-8422-4b29-a92c-c20407e9c882">

Am I missing something?

**Comment by asottile** [comment]
please search your error message here you'll find a duplicate with an explanation!
