### ISSUE TITLE
Commit keywords to skip pre-commit ci seemingly not working

### ISSUE THREAD

**Issue by alyssadai** [pre-commit-ci/issues#224]
Hi @asottile,

We have pre-commit CI enabled for repos where we have automatic releases based on PR labels, and are encountering an issue where pre-commit CI is running and then failing on PRs to update the CHANGELOG.md, which are auto-opened and then auto-merged whenever a release is made. This happens even though we have added keywords to skip pre-commit CI in the changelog commit message (we tried both `[skip ci]` alone and `[skip pre-commit.ci] [skip ci]`).

Example:
- PR where pre-commit CI fails: https://github.com/neurobagel/federation-api/pull/101
  - offending commit: https://github.com/neurobagel/federation-api/commit/5b3350e2886a3b94dbc5ea74dbba503e5cf85aed
- pre-commit CI error we get:
  ![image](https://github.com/user-attachments/assets/7e4173b8-0ad9-458c-b895-dabf7efc1750)
  (https://results.pre-commit.ci/run/github/697817508/1718914180.yLV1EymUT6qxQoyy4aS8hQ)

Any idea on why the skip keywords are not working in this case to stop pre-commit CI from running in the first place?

**Comment by asottile** [comment]
that status check is from the pull request itself (`pre-commit.ci - pr`) -- since you're doing a fast-forward merge it will still appear in the main branch (this is just how github works) -- you could switch to squash merge and it would create a new commit and erase that status.

I don't believe there's a way to accomplish what you're looking for.  pre-commit ci is always enabled on PRs and skipping is only for main branch commits (you'll notice there isn't a `pre-commit.ci - push` status on your mainline commit -- meaning skip is working there).

the error you're seeing is because the merge happened before the run started

**Comment by asottile** [comment]
though at that point not sure why even bother with a pull request -- just apply the commit directly to main?

**Comment by alyssadai** [comment]
Thanks for the insights @asottile.

We have branch protection on for the `main` branch so direct commits without a PR are not really possible. I've since tried tinkering with our release wf to manually allow & disallow bypassing branch protection as part of the workflow run itself, to try and force the auto CHANGELOG updates (which are what cause conflicts with pre-commit CI) to be committed directly, but this doesn't really seem to work. 

Given that pre-commit CI is unfortunately the primary blocker causing our main branch to be red whenever we release, due to not being able to be skipped for PRs, I think we may have to simply disable pre-commit CI for now until we can figure out some workaround.

I understand from https://github.com/pre-commit-ci/issues/issues/31 that you at one point considered honoring skip CI for PRs in addition to main branch commits (?, not sure if I read that correctly). Any further consideration to this feature would be much appreciated, as I think there are cases when using GH automation & branch rules where being able to skip pre-commit would be very useful. Thanks again!

**Comment by asottile** [comment]
it would be possible by PR title I think, but not from commit message?

there are options to give a special user branch protection bypass (since that's effectively what's happening here anyway) -- we use it at sentry for force merges with a special user while still requiring everyone else to go through the process

**Comment by alyssadai** [comment]
> it would be possible by PR title I think, but not from commit message?

Interesting - to clarify, do you mean that if I added the skip keywords to the PR title, pre-commit CI may ignore it in its current version?

> there are options to give a special user branch protection bypass (since that's effectively what's happening here anyway) -- we use it at sentry for force merges with a special user while still requiring everyone else to go through the process

Indeed, this is what I was trying as well, including using my own PAT with administrator permissions. The problem for us is that the CHANGELOG is generated and committed by another package we're using in our workflow (intuit/auto), and afaik it doesn't ever force push or provide the option to (probably for safety reasons). I suspect the use of 'normal' pushes is why the bypass settings aren't having any effect. But of course, perhaps with more digging something is possible without having to control that release logic ourselves.

**Comment by asottile** [comment]
> > it would be possible by PR title I think, but not from commit message?
> 
> Interesting - to clarify, do you mean that if I added the skip keywords to the PR title, pre-commit CI may ignore it in its current version?

nah, just a theoretical "it could be implemented given the data available"

> Indeed, this is what I was trying as well, including using my own PAT with administrator permissions. The problem for us is that the CHANGELOG is generated and committed by another package we're using in our workflow (intuit/auto), and afaik it doesn't ever force push or provide the option to (probably for safety reasons). I suspect the use of 'normal' pushes is why the bypass settings aren't having any effect. But of course, perhaps with more digging something is possible without having to control that release logic ourselves.

it shouldn't need a force push in my experience -- [sentry's is just a normal push](https://github.com/getsentry/sentry/blob/159d52c5273b0d6b326e3b2669635cd4a880d0a7/.github/workflows/bump-sentry-in-getsentry.yml#L46) -- but it does need to be the right _user_ doing the push, and that user has to have a custom role which allows the action to happen

**Comment by alyssadai** [comment]
Good news, I figured out why a normal push wasn't working for us for the CHANGELOG update. It was because even though the user whose token we were using for the release step had branch protection bypass, we didn't provide that token during the earlier `actions/checkout` step of the workflow, i.e.:

```
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.MY_TOKEN }}
```

looks like without that last line, the credentials in subsequent steps were not sufficient for auth. Neato. 

With that fix, the changelog is now being committed directly to `main` upon release, meaning that pre-commit CI is able to be skipped.

Thanks again for your help!

**Comment by asottile** [comment]
sweet!  good to hear \o/
