### ISSUE TITLE
Option to use Windows images

### ISSUE THREAD

**Issue by seanbudd** [pre-commit-ci/issues#225]
We have a Windows development set-up and require Windows batch scripts to be runnable for some of our checks.
It would be great if there was an option to use Windows images for pre-commit.ci.
Thanks for considering this!

**Comment by asottile** [comment]
sorry this won't be happening -- perhaps PowerShell will be supported but I unfortunately can't run windows

**Comment by asottile** [comment]
you may be able to use https://pre-commit.ci/lite  though -- it should work though is untested on windows

**Comment by seanbudd** [comment]
No problem - thanks for responding
