### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by cdwilson** [pre-commit-ci/issues#227]
I'm seeing a couple failures in hooks that try to download schemas for validating JSON & YAML files. The hooks run fine on my local machine, but fail when running on pre-commit.ci.

I'm seeing errors like these:

```
Failed to resolve 'json.schemastore.org' ([Errno -3] Temporary failure in name resolution)
```

```
Failed to resolve 'raw.githubusercontent.com' ([Errno -3] Temporary failure in name resolution)
```

Here's a link to an example failing run: https://results.pre-commit.ci/run/github/827662191/1724168677.vhcIuoHaTZuyXXOYqmIZxw

**Comment by asottile** [comment]
please search the issue tracker there are several duplicates (try your error message!)

**Comment by cdwilson** [comment]
Thanks, my apologies!
