### ISSUE TITLE
Using pre-commit.ci for automatic hook updates only

### ISSUE THREAD

**Issue by cdwilson** [pre-commit-ci/issues#228]
I initially started using [pre-commit.ci](https://pre-commit.ci/) on an open-source repo, which worked great until I added a couple hooks which [require network access at runtime](https://github.com/pre-commit-ci/issues/issues/47#issuecomment-804481763).

To allow these hooks to run, I switched to using [pre-commit.ci lite](https://pre-commit.ci/lite.html) in GHA, following the [example using `pre-commit/action`](https://pre-commit.ci/lite.html#example-using-pre-commit-action). This appears to be working great as well.

However, I'd still like to get the periodic automatic hook updates PRs provided by the [pre-commit.ci](https://pre-commit.ci/) service.

Reading other issues here (e.g. https://github.com/pre-commit-ci/issues/issues/131#issuecomment-1164321551), it looks like `skip` is the intended mechanism for this.

I thought about simply adding all the hooks to the `skip: []` list, but I'd like to avoid manually maintaining that list each time I add or remove a hook.

Would you be open to adding an option like `skip: all` or some other mechanism to disable running all hooks on [pre-commit.ci](https://pre-commit.ci/)? This would make it easier to prevent unnecessary runs on [pre-commit.ci](https://pre-commit.ci/) when the hooks are already run via GHA or elsewhere.

BTW, thanks for providing this service!

**Comment by asottile** [comment]
I don't want to encourage things like that -- it costs me money to recieve webhooks and perform a noop build (not to mention it wastes shared resources).  especially for free tier

I'd instead recommend fixing your hooks to not require network at runtime -- as you're doing your contributors a disservice by making their experience slow, potentially flaky, and difficult to commit on an airplane (even if they've cached the environments!)

**Comment by cdwilson** [comment]
> I'd instead recommend fixing your hooks to not require network at runtime -- as you're doing your contributors a disservice by making their experience slow, potentially flaky, and difficult to commit on an airplane (even if they've cached the environments!)

I didn't think about that, thanks for the insight! (this changed the way I think about the role of pre-commit in general) I'm going to update my pre-commit config to remove the hooks that require network access and move this stuff into CI instead.
