### ISSUE TITLE
Make the badge available as a JSON endpoint

### ISSUE THREAD

**Issue by paduszyk** [pre-commit-ci/issues#230]
As far as I see (sorry if I'm wrong), there is no way to customize how the badge is displayed — the URL on the results page links to an SVG.

I am just wondering: Would it be possible to provide access to the label via JSON endpoint (in the way, some other tools offer it, e.g. [Ruff](https://github.com/astral-sh/ruff?tab=readme-ov-file#show-your-support))? If so, one could customize the badge's style, e.g. via Shields.io.

**Comment by asottile** [comment]
at this time I don't really want to provide an unregulated api for this information -- the badges already dominate the web traffic and I don't really want to make that worse for free
