### ISSUE TITLE
Configure `pre-commit.ci` pull-request labels

### ISSUE THREAD

**Issue by bjlittle** [pre-commit-ci/issues#231]
Would it be possible to extend the configuration within the `.pre-commit-config.yaml` to allow he ability for maintainers to set one or more labels on the pull-request generated by `pre-commit.ci` ?

This is akin to the `autoupdate_commit_msg` that sets the title of the pull-request generated by the `pre-commit.ci` service.

My specific use-case is that I want to be able to ignore all bot generated pull-requests with the `skip changelog` label i.e., don't perform quality assurance GHA checks on a bot pull-request as there will be no `towncrier` changelog news fragments.

For example, this is possible to configure `dependabot` with labels, and it would be pretty awesome if `pre-commit.ci` could offer this behaviour too.

Many thanks

**Comment by asottile** [comment]
please search for duplicates!
