### ISSUE TITLE
Unclear how to install prerequisites

### ISSUE THREAD

**Issue by djmitche** [pre-commit-ci/issues#232]
I have a pretty simple Rust app, https://github.com/GothenburgBitFactory/taskchampion-sync-server, to which I'd like to apply pre-commit.  It has a `Cargo.toml` at the top level, which seems to be expected -- although I'm unclear if that's required in the hook repo or the repo to which pre-commit is being applied?

In https://github.com/GothenburgBitFactory/taskchampion-sync-server/pull/33 I added `.pre-commit-config.yaml`:
```yaml
repos:
-   repo: https://github.com/FeryET/pre-commit-rust
    rev: v1.1.1
    hooks:
    -   id: fmt
    -   id: cargo-check
    -   id: clippy
```
and it fails with [this error](https://results.pre-commit.ci/run/github/783481734/1722131970.xXcMRCJPTbCVlEHlAN_gnQ):
```
fmt......................................................................Failed
- hook id: fmt
- exit code: 1

Executable `cargo` not found

cargo check..............................................................Failed
- hook id: cargo-check
- exit code: 1

Executable `cargo` not found

clippy...................................................................Failed
- hook id: clippy
- exit code: 1

Executable `cargo` not found
```
it's unclear to me, even after reading the "rust" section in [the docs](https://pre-commit.com/#rust), what I should do to get this to run in `pre-commit.ci`. The hook itself is not written in Rust, so I don't think those instructions apply to it. But I tried adding `language: rust` as you can see in the PR history, and that just adds a warning to the `pre-commit.ci` failure:
```
[WARNING] Unexpected key(s) present on https://github.com/FeryET/pre-commit-rust: language
```
I filed [an issue](https://github.com/FeryET/pre-commit-rust/issues/2) for the hook repo, but either the authors have never heard or pre-commit.ci, or I'm asking such a fundamentally dumb question that they could not comprehend.

Help?

**Comment by djmitche** [comment]
I guess "Help?" isn't a question, so I'll ask more precisely:

How can I do basic checks on a simple Rust repo in pre-commit.ci?

**Comment by asottile** [comment]
that repository is not supported on pre-commit.ci -- it uses `language: system` which generally is "at your support" (aka unsupported) -- you would need to find a `language: rust` version of those hooks

alternatively you can use pre-commit.ci lite which runs on github actions and then you can do whatever provisioning you want
