### ISSUE TITLE
Autoupdate creates broken YAML

### ISSUE THREAD

**Issue by Holzhaus** [pre-commit-ci/issues#235]
The pre-commit.ci autoupdater opened a PR with changes that broke the YAML config: https://github.com/sphinx-contrib/multiversion/commit/47938e1a8f433487afdc2ab21f3fdf94068a03f8

It replaced the `commit` stage like this:
```diff
     stages:
-    - commit
+    - Nonepre-commitNone
```

This PR was affected: https://github.com/sphinx-contrib/multiversion/pull/125 (change was correct with force-push).

**Comment by asottile** [comment]
this is a duplicate of #234 -- please search next time!

**Comment by Holzhaus** [comment]
Sorry, didn't see it because it was already closed and I didn't expect the issue to be fixed already. Thanks!
