### ISSUE TITLE
pre-commit-ci can't find python 3.8

### ISSUE THREAD

**Issue by mkrakowiak-luminar** [pre-commit-ci/issues#237]
Hey,
Today we've noticed that pre-commit-ci started failing for our repo at the build stage:
```
    [INFO] Installing environment for local.
    [INFO] Once installed this environment will be reused.
    [INFO] This may take a few minutes...
    An unexpected error has occurred: CalledProcessError: command: ('/venv/bin/python3', '-mvirtualenv', '/pc/clone/SK36nMk5QvmyeQ_lr1eQMg/py_env-python3.8', '-p', 'python3.8')
    return code: 1
    stdout:
        RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.8'
    stderr: (none)
    Check the log at /pc/pre-commit.log
```
https://results.pre-commit.ci/run/github/820078473/1729498929.-RCkO8VPSSKM5EQID2c-7w

By the way, this works with runner image 2024-10-11-d1d12eb but not with [2024-08-26-7d4d12e](https://results.pre-commit.ci/run/github/820078473/1727747335.VHvFkLdrSRyJLB5UXsqaKA). 

Do you have any idea what might be going wrong?

**Comment by asottile** [comment]
python 3.8 has reached end of life and so it was removed
