### ISSUE TITLE
pre-commit.ci times out for large repositories.

### ISSUE THREAD

**Issue by domdfcoding** [pre-commit-ci/issues#25]
Hi,

I've got a repository which is about 600MB in size. pre-commit runs fairly slowly locally (~40s with `--all-files`) but times out pre-commit.ci.

See, for example https://results.pre-commit.ci/run/github/267001384/1606145380.1zQbhL--QhC6uTm6Rp12UQ

Is there a way to make the pre-commit.ci run quicker so they don't time out? If not, could you add an option to exclude certain directories from the ci runs but still check them locally?

Thanks

**Comment by asottile** [comment]
hmm I wonder if there's particular things in the repository that are slowing things down -- 180s is pretty lenient

at some point I do plan on moving off of t2.micros to beefier machines -- maybe today is the day?

**Comment by asottile** [comment]
looks like it gets further now with the larger instance sizes -- but still times out before completing :'(

**Comment by asottile** [comment]
I sent a PR to fix OP's repository: https://github.com/PyMassSpec/pyms-agilent/pull/18

in general this should be "done" enough
