### ISSUE TITLE
Add shellcheck command to support shell-lint hook

### ISSUE THREAD

**Issue by danyeaw** [pre-commit-ci/issues#27]
Checks using the shell-lint pre-commit hook are failing because pre-commit-ci doesn't have the shellcheck command available:
https://results.pre-commit.ci/run/github/235448/1606152698.vuViAVHoRQ-LIGY84k5kQg

The same check is passing on GitHub Actions:
https://github.com/gaphor/gaphor/pull/521/checks?check_run_id=1443504111

**Comment by asottile** [comment]
Use https://github.com/shellcheck-py/shellcheck-py

**Comment by asottile** [comment]
pre-commi.ci won't be installing ad-hoc `system` tools -- `language: system` / `language: script` is the escape hatch for pre-commit

**Comment by danyeaw** [comment]
@asottile Thanks, I didn't know about shellcheck-py, I'll give that a spin :+1:
