### ISSUE TITLE
Custom commit msg for autoupdates

### ISSUE THREAD

**Issue by Cielquan** [pre-commit-ci/issues#36]
I'm transitioning towards using [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) messages for automated version bumping (semver) and changelog generation. Therefore it would be nice if one could customize the commit message set by the autoupdate pipeline: `[pre-commit.ci] pre-commit autoupdate`.

I e.g. would change it to `chore(pre-commit) [pre-commit.ci] pre-commit autoupdate`.

**Comment by asottile** [comment]
this'll probably require a configuration setting which I kind of want to hold off on until I've established quite how that'll work

this also ties in with #32 as to how this will work out.  it may also relate to #24 for labeling PRs which might change how this fits together

I don't really have an estimate as to when this could happen, but I also think it's probably not a priority.  The commits made by pre-commit.ci don't really fall into changelog-relevant stuff so it's lower priority (personally I think "conventional commits" is fundamentally flawed but I won't bother having that discussion here!)

as a workaround if you really need this functionality today you could probably utilize a github action to amend the message if needed

**Comment by Cielquan** [comment]
Yeah I thought that this would be a thing for the config part you mentioned earlier (if you implement it):
> A better design that I'm thinking about is a top level `ci:` mapping -- that way pre-commit does not need to be updated repeatedly to allowlist more and more options as they get added

And another workaround I forgot to mention are squash-merges. So this feature does not have a high priority for myself either.

---

I would like to hear your opposing reasons for "conventional commits". I will write you an email to the address from you commits.

**Comment by asottile** [comment]
you can now configure this through [`ci: autoupdate_commit_msg: ...`](https://pre-commit.ci/#configuration-autoupdate_commit_msg)

thanks for the issue!
