### ISSUE TITLE
weird time rounding

### ISSUE THREAD

**Issue by neutrinoceros** [pre-commit-ci/issues#38]
Hi there ! just noticed a weird timestamp for a 2min long run, thought it might be considered a bug (although it is technically correct).

![Screen Shot 2021-01-13 at 16 32 11](https://user-images.githubusercontent.com/14075922/104473164-f8b8b800-55bc-11eb-90cf-26cf0ca0f2d8.png)

**Comment by asottile** [comment]
good eye!  yep I'll fix this, it's an interesting edge case

**Comment by asottile** [comment]
Alrighty this has been fixed!

- [used to say 1m60s](https://results.pre-commit.ci/run/github/88776493/1610549593.hn5ZReucRQWOHThKJWiOQQ)
- [used to say 2m0s](https://results.pre-commit.ci/run/github/88776493/1610549751.6CF1kgUYTt-hP0UCequrGA)
