### ISSUE TITLE
pre-commit.ci forgot about fixing my commit ?

### ISSUE THREAD

**Issue by neutrinoceros** [pre-commit-ci/issues#39]
Hi Anthony,

In this PR https://github.com/yt-project/yt/pull/2978 I noticed that pre-commit.ci ran and failed but apparently didn't commit to my branch.
Here's the permanent link to pre-commit.ci's results
https://results.pre-commit.ci/run/github/88776493/1610706505.XiBbJypzR0ab0PPZQx4dBw

Maybe it's a chance event, in which case I'm leaving the PR in question in its current state if it's any help for you understand what went wrong.

**Comment by asottile** [comment]
this looks like you haven't accepted the updated permissions -- modifications to `.github/workflows` require you to authorize pre-commit.ci to "write" to workflows

this was added after the initial launch so you should have gotten an update for your organization -- this was handled through #14

I believe you can accept the new permissions from the install page?  I think that's this page for your org: https://github.com/apps/pre-commit-ci/installations/14062031

**Comment by asottile** [comment]
huh actually you have all the permissions set up properly: `'permissions': {'issues': 'read', 'contents': 'write', 'metadata': 'read', 'statuses': 'write', 'workflows': 'write', 'pull_requests': 'write'}`

looking at the logs it looks like it hit the github api race condition again.  github has a bug right now where they hand out an installation token and it doesn't consistently get write permissions until many seconds later.  I've got a bunch of retries in place and github claims they're working on a fix but there's nothing I can really do about it :(

if you close + reopen your pull request it should re-trigger the push

**Comment by neutrinoceros** [comment]
> if you close + reopen your pull request it should re-trigger the push

well it didn't :(
But I understand the issue is not on your side. If there's an open discussion somewhere I'm interested, but in any case you can close this if you wish. :)
Thanks for your support, I appreciate it !

**Comment by asottile** [comment]
huh ok I was looking at the wrong logs, this definitely looks like a different github bug:

```
Jan 15 10:30:27 ip-172-31-25-240 python3[377]: ====> pushing...
Jan 15 10:30:57 ip-172-31-25-240 python3[595016]: [bump_test_python39 33db6fe97] [pre-commit.ci] auto fixes from pre-commit.com hooks
Jan 15 10:30:57 ip-172-31-25-240 python3[595016]:  Date: Fri Jan 15 10:30:27 2021 +0000
Jan 15 10:30:57 ip-172-31-25-240 python3[595016]:  1 file changed, 1 insertion(+), 1 deletion(-)
Jan 15 10:30:57 ip-172-31-25-240 python3[377]: =======> cherry picked!
Jan 15 10:30:59 ip-172-31-25-240 python3[595019]: To https://github.com/neutrinoceros/yt
Jan 15 10:30:59 ip-172-31-25-240 python3[595019]:  ! [remote rejected]     HEAD -> bump_test_python39 (refusing to allow a GitHub App to create or update workflow `.github/workflows/build-test.yaml` without `workflows` permission)
Jan 15 10:30:59 ip-172-31-25-240 python3[595019]: error: failed to push some refs to 'https://x-access-token:<<SNIPPED>>@github.com/neutrinoceros/yt'
Jan 15 10:30:59 ip-172-31-25-240 python3[377]: =======> push failed :(
Jan 15 10:31:04 ip-172-31-25-240 python3[595025]: To https://github.com/neutrinoceros/yt
Jan 15 10:31:04 ip-172-31-25-240 python3[595025]:  ! [remote rejected]     HEAD -> bump_test_python39 (refusing to allow a GitHub App to create or update workflow `.github/workflows/build-test.yaml` without `workflows` permission)
Jan 15 10:31:04 ip-172-31-25-240 python3[595025]: error: failed to push some refs to 'https://x-access-token:<<SNIPPED>>@github.com/neutrinoceros/yt'
Jan 15 10:31:04 ip-172-31-25-240 python3[377]: =======> push failed :(
Jan 15 10:31:08 ip-172-31-25-240 python3[595031]: To https://github.com/neutrinoceros/yt
Jan 15 10:31:08 ip-172-31-25-240 python3[595031]:  ! [remote rejected]     HEAD -> bump_test_python39 (refusing to allow a GitHub App to create or update workflow `.github/workflows/build-test.yaml` without `workflows` permission)
Jan 15 10:31:08 ip-172-31-25-240 python3[595031]: error: failed to push some refs to 'https://x-access-token:<<SNIPPED>>@github.com/neutrinoceros/yt'
Jan 15 10:31:08 ip-172-31-25-240 python3[377]: =======> push failed :(
```

**Comment by asottile** [comment]
I've opened a support ticket with github

**Comment by asottile** [comment]
this appears to be fixed on github's side!  https://github.com/asottile2/demo2_wat/pull/13/commits/549d71b1c829e53bc91b45de715eacc6863becd7
