### ISSUE TITLE
Retrigger the check

### ISSUE THREAD

**Issue by lachmanfrantisek** [pre-commit-ci/issues#42]
Would it be possible to react on some pull-request comment (e.g. `/pre-commit-ci`, ...) and retrigger the check?

[Sometimes](https://results.pre-commit.ci/run/github/201919335/1612803083.4JVF9WGRTMGu84B5HAuqHQ) the build fails, and we want to retrigger it to see if it is a flake or real issue. Or, run it again once it's fixed on the other side.

One can push to the PR again, but with external contributors (including the scheduled config updates from pre-commit-ci) is not so convenient.

Thanks in advance!

**Comment by asottile** [comment]
from [pre-commit.ci](https://pre-commit.ci/):

> **re-running a pull request**: you can trigger a re-run on a pull request by closing and re-opening.

note that `ansible-lint` is much much too big to work with pre-commit.ci right now -- upstream needs to publish wheels so their installation doesn't take 5 minutes: https://github.com/ansible/ansible/issues/73043

**Comment by lachmanfrantisek** [comment]
> from [pre-commit.ci](https://pre-commit.ci/):

OK, thanks for the info. That's not ideal but at least something.

> note that ansible-lint is much much too big to work with pre-commit.ci right now  ...

Yes, that was just an example. Nevertheless, thanks for the link (and creation) of the upstream issue.

**Comment by asottile** [comment]
you can now re-trigger a PR by commenting `pre-commit.ci run` on a pull request: https://github.com/pre-commit-ci/pre-commit.ci/pull/23

**Comment by lachmanfrantisek** [comment]
Nice! Thank you for implementing this!
