### ISSUE TITLE
Add option to disable submodules checkout

### ISSUE THREAD

**Issue by nijel** [pre-commit-ci/issues#43]
Right now pre-commit-ci seems to checkout all submodules. This can fail or just slow down the build and it would be useful to turn this off in case it's not needed.

I've run into this in https://results.pre-commit.ci/run/github/116816146/1612858774.myIqOmUUTmGB06u0oFig9w where the submodules update fails (what might be a separate issue).

When I try it locally with `git submodule update --init --recursive` it works, but it takes quite long and there is no need to run this on pre-commit.ci as the submodules are neither supposed to be checked nor are needed for the pre-commit checks.

**Comment by nijel** [comment]
Having something similar as [GitHub checkout action](https://github.com/actions/checkout) has would do that - set  `submodules` to `false` / `true` / `recursive` would work. They have default to not checkout submodules, maybe it would be reasonable default for pre-commit.ci as well to avoid needlessly cloning submodules unless the user wants them.

**Comment by asottile** [comment]
I've split the bug portion to #44

**Comment by asottile** [comment]
submodules are now disabled by default and opt-in: https://pre-commit.ci/#configuration-submodules
