### ISSUE TITLE
pre-commit.ci overwrites changes made to its autoupdates.

### ISSUE THREAD

**Issue by tobiasraabe** [pre-commit-ci/issues#49]
Hi,

thanks for the awesome service!

I have a minor issue with the service and it is that the bot updates open PRs with autoupdates using force pushes.

See this [PR](https://github.com/pytask-dev/pytask/pull/73) where I fixed something related to an updated hook and the bot overwrote the changes with the next autoupdate.

Can the bot be more careful in these situations?

**Comment by asottile** [comment]
you can always recover the changes by reverting the force push, the autoupdate happens once a week which should give you plenty of time to integrate the branch
