### ISSUE TITLE
Outdated schema on JSONSchema store

### ISSUE THREAD

**Issue by ad-m** [pre-commit-ci/issues#50]
Hello,

Schema available at https://json.schemastore.org/pre-commit-config.json is outdated. It does not cover `ci` section at all.

I don't have knowledge about `ci` to fix that. I was looking for schema to get that knowledge.

Kind regards,

**Comment by asottile** [comment]
I am not affiliated with that schema source -- you should not trust it for correctness -- I would not recommend using it.

If you want validation, it is available in the following canonical places:

via `pre-commit` (pypi:
- `pre-commit-validate-config` - validates a `.pre-commit-config.yaml`
- `pre-commit-validate-manifest` - validates a `.pre-commit-hooks.yaml`

via `pre-commit-ci-config` (pypi):
- `check-pre-commit-ci-config` - validates the `ci` section of a `.pre-commit-config.yaml`

**Comment by asottile** [comment]
it's also incorrect for several other reasons (top-level variability, type checking, choices, etc.) that aren't representable in json schema
