### ISSUE TITLE
Automerge of autoupdates

### ISSUE THREAD

**Issue by ad-m** [pre-commit-ci/issues#51]
Hello,

I would like suggess add support for automerge of updates like https://github.com/watchdogpolska/feder/pull/984/files when all CI (not only `circle-ci`) tests pass.

See Renovate `automerrge` documentation: https://docs.renovatebot.com/configuration-options/#automerge

Kind regards,

**Comment by asottile** [comment]
duplicate, please [search the issue tracker next time](https://github.com/pre-commit-ci/issues/issues?q=is%3Aissue+auto+merge+is%3Aclosed)

**Comment by cpsauer** [comment]
For anyone else arriving here looking, the original issue is #48.
(This one came up first in my search.)
