### ISSUE TITLE
Button for "Apply pre-commit changes" 

### ISSUE THREAD

**Issue by kolibril13** [pre-commit-ci/issues#52]
# Idea
At the moment, pre-commit.ci changes are directly committed to a branch:
![image](https://user-images.githubusercontent.com/44469195/114019279-7ca5d780-986e-11eb-8c32-e40f54e41f64.png)
To give more control to the user, It might be nice to have an optional button in GitHub called for example "Apply pre-commit changes" , similar to the "Ready for review", or "Update branch" button.
![image](https://user-images.githubusercontent.com/44469195/114019414-a7902b80-986e-11eb-920d-b51749d1da24.png)
# Motivation
Here is a possible situation where this could be useful and avoid confusion (e.g. assuming that pr-commit includes black formatting).
1. A contributor writes unformatted code and pushes it to a pull request - branch that has pr-commit.ci enabled.
2. pre-commit.ci will autoformat and add another commit, but the contributor does not pull the latest changes.
3. The contributor writes some more unformatted code and makes another commit. 
4. When the contributor tries to push this new commit, there will be a lot of merge conflicts.

With the new button, the code formatting could only be applied at the end of the pull request review process, and there won't be any probably unexpected changes on the branch by the pr-commit.ci bot.  

But also without this button `pr-commit.ci` is already a great feature, especially for auto-formatting the code after applying code changes from the online code suggestion on GitHub.

**Comment by asottile** [comment]
if the contributor force pushes their changes they won't have a problem (it will reformat their stuff)

that said, I'm currently in the process making this workflow possible:

- (1) configure `autofix_prs: false`
- (2) manually trigger autofix runs via `pre-commit.ci autofix` comment

**Comment by asottile** [comment]
this is now implemented -- you can do just as I said above !
