### ISSUE TITLE
Increase session timeout?

### ISSUE THREAD

**Issue by adamchainz** [pre-commit-ci/issues#54]
I have returned to pre-commit.ci several times today and had to click the "Sign in with GitHub" button each time. Perhpas the session timeout could be longer - even 12 hours would be good.

**Comment by asottile** [comment]
hmmmm did you perhaps close the browser between sessions?  the current ttl is set to 5 days (which, in my testing causes the session to last up-to 7 days due to the way dynamodb's ttl thing works)

**Comment by asottile** [comment]
in the database, I only see a single session for you at the moment 🤔

**Comment by adamchainz** [comment]
I figured it out - I am logged in, but I keep visiting https://pre-commit.ci/ which shows no indication of "you're already signed in", only the sign in button. Clicking that redirects me through GitHub every time, with a noticeable delay.

**Comment by asottile** [comment]
ohhhh!  I can maybe short circuit that if you're already logged in -- I can probably do that today on stream

the website at https://pre-commit.ci is entirely static (hosted on github pages) to make it easier to deploy and separate from the api portions -- but I can make that login redirect tighter (skip github when not needed)

**Comment by asottile** [comment]
alrighty! this should be done now, it checks if you're logged in already and redirects you straight to the homepage instead of going through github's slow stuff

**Comment by adamchainz** [comment]
Works well for me!
