### ISSUE TITLE
ability to uninstall/suspend pre-commit.ci GitHub app from pre-commit.ci UI

### ISSUE THREAD

**Issue by graingert** [pre-commit-ci/issues#6]
I've managed to get into a tricky situation on https://results.pre-commit.ci/install/github/12624072 where I have permissions to install the app - but no permission to uninstall the app

It should be possible by calling https://docs.github.com/en/free-pro-team@latest/rest/reference/apps#delete-an-installation-for-the-authenticated-app

Another option would be to allow owners to "pause" the job in pre-commit.ci, then builds will stop being run until they are unpaused

**Comment by graingert** [comment]
Currently https://pre-commit.ci provides a link to manage the GitHub app installation: https://github.com/organizations/twisted/settings/installations/12624072 but that 404s for me

**Comment by asottile** [comment]
sadly I don't want to extend the privileges beyond what github gives you otherwise that is a privilege escalation

consider:
- you add the installation for twisted
- someone else adds a repository outside of your control to the installation
- you delete installation

**Comment by graingert** [comment]
@asottile how about just this bit

> Another option would be to allow owners to "pause" the job in pre-commit.ci, then builds will stop being run until they are unpaused

**Comment by asottile** [comment]
what do you mean by "pause"?  also I don't know how to cheaply determine if someone is an owner or not -- the apis afforded to github apps are pretty slim (the idea I believe being that github is supposed to  manage all of this and permissions properly).  the webhooks don't contain this information for example

ideally I'd prefer you go to your organization owner and have them disable it as github intended

**Comment by graingert** [comment]
> what do you mean by "pause"?

Have pre-commit.ci ignore messages from the webhook until the "pause" option is toggled

**Comment by asottile** [comment]
I still pay money out of pocket to run the webhook so that's not really a solution

**Comment by graingert** [comment]
> Hi there Thomas,
>
> Thanks for writing in!
>
> Because you're not an organisation owner, the "Manage repos" link used by pre-commit.ci will return a 404. It is still possible for a repository admin to manage the GitHub App, and uninstall it, but via a slightly different route.
>
> If you head back to the installation page (via the "add an installation" link on pre-commit.ci), you'll see a "Configure" by any accounts or organisations that you've installed the app on. If you click that, you'll be able to add and remove the GitHub app.
>
> I hope that's helpful! I'm going to open an issue for our team too, to see if will be possible to expose this page to repository admins when they follow a link intended for organisation owners. I can't make any promises about changes here but I'll make sure it's in good hands!
>
> Best regards,
> Steve

I got it uninstalled by following the guide from github support

The URL I needed to uninstall from twisted was: https://github.com/apps/pre-commit-ci/installations/new/permissions?target_id=716546

**Comment by asottile** [comment]
hmmm ok this is happening to me now with https://github.com/sass (since I'm not an admin there) -- it's really weird to me that github exposes one of those endpoints but not the other -- did staff follow up on whether that's getting fixed or should I stop using the url the api tells me to use?

**Comment by graingert** [comment]
@asottile that's all the message I got

**Comment by asottile** [comment]
this should be fixed now!  thanks for the report

I'm using this url format now:

```
https://github.com/apps/{app}/installations/{install_id}
```
