### ISSUE TITLE
pre-commit.ci timing out when passes locally

### ISSUE THREAD

**Issue by matthewfeickert** [pre-commit-ci/issues#62]
:wave: Hi. `pre-commit.ci` is failing by timeout for PR https://github.com/scikit-hep/pyhf/pull/1403 when it passes locally in a fresh virtual environment (and also passes in `pre-commit.ci` but then timesout).

c.f. https://results.pre-commit.ci/repo/github/118789569

[![pre-commit_failure](https://user-images.githubusercontent.com/5142394/116309013-dc0c4e80-a76d-11eb-9526-cf4ee60e0451.png)](https://results.pre-commit.ci/repo/github/118789569)

and for a particular failing run

[![run_failure](https://user-images.githubusercontent.com/5142394/116309109-f80ff000-a76d-11eb-97d8-2524aee20769.png)](https://results.pre-commit.ci/run/github/118789569/1619554600.JJMtFsPcTd6NzwIP8rvUZw)

This is probably just transitory issue, but thought I'd still report it. 

cc @lukasheinrich @kratsg

---

Also example of my claim that `pre-commit` passes locally:

```
(base) $ git checkout feat/clean-public-api-all  # Branch for the PR that is failing
(base) $ pyenv virtualenv 3.8.7 test-pre-commit
(base) $ pyenv activate test-pre-commit 
(test-pre-commit) $ pip install --upgrade pip setuptools wheel
(test-pre-commit) $ pip install pre-commit
(test-pre-commit) $ pre-commit run --all-files
Check for added large files..............................................Passed
Check for case conflicts.................................................Passed
Check for merge conflicts................................................Passed
Check for broken symlinks................................................Passed
Check JSON...............................................................Passed
Check Yaml...............................................................Passed
Check Toml...............................................................Passed
Check Xml................................................................Passed
Debug Statements (Python)................................................Passed
Fix End of Files.........................................................Passed
Mixed line ending........................................................Passed
Fix requirements.txt.................................(no files to check)Skipped
Trim Trailing Whitespace.................................................Passed
black....................................................................Passed
blacken-docs.............................................................Passed
flake8...................................................................Passed
pyupgrade................................................................Passed
nbqa-black...............................................................Passed
nbqa-pyupgrade...........................................................Passed

**Comment by asottile** [comment]
very strange, timings do look elevated today according to my metrics -- let me look into whether something changed

**Comment by matthewfeickert** [comment]
I doubt this matters much, but the 3 shown timeouts above are happening at different stages:

- [timeout on `pyupgrade`](https://results.pre-commit.ci/run/github/118789569/1619553634._mmDFUcFRb2JvMSjy4FgNw)
- [timeout on `flake8`](https://results.pre-commit.ci/run/github/118789569/1619553859.x45yk5WbTkGSQPfvIxP1wQ)
- [timeout on `nbqa-pyupgrade`](https://results.pre-commit.ci/run/github/118789569/1619554600.JJMtFsPcTd6NzwIP8rvUZw)

**Comment by matthewfeickert** [comment]
@asottile [retriggering the run from the GitHub comments](https://github.com/scikit-hep/pyhf/pull/1403#issuecomment-827932219) has things passing now (after a long queue time): https://results.pre-commit.ci/run/github/118789569/1619557729.aLz8qBFvTBiIxfXakvechw

**Comment by asottile** [comment]
yeah the queue makes sense, I was kicking off a bunch of runs at the same time while the hosts were cycling.

there were no code changes during the period that led to higher timeouts, I suspect one of the hosts got a noisy neighbor in aws:

![image](https://user-images.githubusercontent.com/1810591/116313572-c9d8e300-a762-11eb-87d0-c04f5c6236e4.png)

I'll be putting in some automated alerts to catch this particular failure mode in the future -- thanks for the report!

I'm going to send a message to the mailing list to make sure others know about this and follow up with a postmortem once I'm comfortable that it is resolved

I'll be watching this closely over the next couple of hours to make sure that fixed it

I'll also be sending out a postmortem entry to the mailing list

**Comment by matthewfeickert** [comment]
Awesome. :) Many thanks for this report and also for being :zap: fast in your feedback and help!

**Comment by asottile** [comment]
marking this all clear, run times have returned to normal after mitigation

___

**postmortem**

_root cause_

unknown

- no code changes occurred before or after the incident or to mitigate the incident
- observable host level metrics (cpu / io) were not elevated on any of the affected hosts

_what went well_

- run-level metrics were extremely helpful for identifying the affected timeframe and validating the fix
- host rotation was quick and easy (already scripted)
- helpful issue created by @matthewfeickert alerting to the problem

_what didn't go well_

- detection: slow and entirely manual
- prevention: unknown what caused the actual root issue

_follow-up_

- detection: add automated alerting for elevated timing
- prevention: investigate larger ec2 instance sizes for performance and to lessen "noisy neighbor" effects

**Comment by Borda** [comment]
Hello, just curious is there is a way how to extend the timeout?
 https://results.pre-commit.ci/run/github/145693916/1622449847.gyQnW8ktQPCcmngXvQmabA
