### ISSUE TITLE
timeout for just adding badge

### ISSUE THREAD

**Issue by Borda** [pre-commit-ci/issues#66]
Hello, great took! I have an n00b question, I thought that the pre-commit is running differentiable so checking only on changed files... We just enabled the bot on the Kornia repo, but it is failing even for just adding a badge to the readme... what are we missing?
See the filing build https://results.pre-commit.ci/run/github/145693916/1622450657.0xCbY4mtSsamARASH9vPtQ

cc: @edgarriba

**Comment by asottile** [comment]
hi @Borda looking into this -- I made some suggestions in this PR but let me see if I can get it under time! https://github.com/kornia/kornia/pull/1038

this repository takes 20+ minutes to run on my laptop as it is which is probably not a good developer experience either way!

**Comment by edgarriba** [comment]
@asottile what machine do you have ? never seen that much time :0 - Suggestions are welcomed in that side too

**Comment by asottile** [comment]
will send a PR!  `yapf` takes nearly a minute on this file alone: `test/augmentation/test_augmentation.py`

**Comment by asottile** [comment]
for context, here's the two PRs:
- https://github.com/kornia/kornia/pull/1051
- https://github.com/kornia/kornia/pull/1052

**Comment by asottile** [comment]
should be good to go now that kornia/kornia#1052 is merged 🎉
