### ISSUE TITLE
Failing to run pre-commit hook

### ISSUE THREAD

**Issue by billsioros** [pre-commit-ci/issues#67]
Hello, 

It is seems there is an issue regarding the [editorconfig-checker.python](https://github.com/editorconfig-checker/editorconfig-checker.python/) pre-commit hook, only while running on CI.

I have opened an issue on `editorconfig-checker.python`' s side as well. For more details please refer to [this issue](https://github.com/editorconfig-checker/editorconfig-checker.python/issues/15).

P.S. I have already tried running the hook with `verbose: true`. Given the aforementioned problem, it seems like it would be a good idea to be able to get traceback's and/or logs whilst running on CI, so that we, users, can more thoroughly investigate such issues ourselves and not bother you with issues like this one 😄 

Thanks in advance,
Vasilis

**Comment by asottile** [comment]
network is not allowed at runtime

**Comment by billsioros** [comment]
Hello again @asottile,

The maintainers of `editorconfig-checker.python` patch the problem, but we are now facing a different issue. The CI fails fails due to the 50MB max-size limit. You may reference our discussion [here](https://github.com/editorconfig-checker/editorconfig-checker.python/issues/15#issuecomment-880721538). More specifically the problem is described [here](https://github.com/editorconfig-checker/editorconfig-checker.python/issues/15#issuecomment-880601995).

This is by no means of critical importance. Just wanted to know if there is a workaround. Thanks! 👋🏽

**Comment by asottile** [comment]
left a comment about a better way to do what they're doing, hopefully they'll fix it 👍
