### ISSUE TITLE
Add latest run status to repo list

### ISSUE THREAD

**Issue by janosh** [pre-commit-ci/issues#68]
Would be nice if the white space to the right in the repo list on pre-commit.ci was used to display stats of the latest run. That way you could see at a glance which repos are passing and which need attention after an autoupdate.

![Screen Shot 2021-07-06 at 20 54 57](https://user-images.githubusercontent.com/30958850/124652592-915d3000-de9c-11eb-99d2-9742c97f6457.png)

**Comment by asottile** [comment]
are you merging failing PRs? I don't see why this would be necessary -- could you elaborate on your workflow?

I ask because displaying that information for all repos is really really expensive and isn't doable -- though I suspect your workflow is flawed

**Comment by janosh** [comment]
> are you merging failing PRs? I don't see why this would be necessary -- could you elaborate on your workflow?

No, but I'd say that info is interesting anyway. Not just whether a run passed or failed but when it ran, how long it took, on which branch etc.

> I ask because displaying that information for all repos is really really expensive and isn't doable

That's unexpected. Why would it be expensive? pre-commit.ci displays that information anyway when clicking on a repo. Could it be cached?

**Comment by asottile** [comment]
the latest N runs are displayed when you click on a repository because there's an easy query for that.  when you have hundreds, thousands of repositories running that query hundreds or thousands of times is not doable

fortunately you don't need that -- you can see the statuses in github's UI directly

**Comment by asottile** [comment]
the last run for a repository also isn't useful information -- it could be the autoupdate PR you want or it could be some unrelated PR or primary branch run

**Comment by janosh** [comment]
I think it would be useful. Just make it the last auto update PR always. But it's not essential and I'm not going to press a point on a great free service if you're saying it's too expensive.￼￼￼
