### ISSUE TITLE
mypy types not installed despite --install-types

### ISSUE THREAD

**Issue by sebhmg** [pre-commit-ci/issues#69]
`mypy` fails on pre-commit.ci with error: `Library stubs not installed for "toml"`
However mypy is configured to run with options `["--install-types", "--non-interactive"]` that are supposed to install the missing types. This does work when running pre-commit inside a github workflow.

See error below:
![image](https://user-images.githubusercontent.com/24550538/125645675-4405e7c6-158f-4122-8be3-11c5434d86b5.png)

**Comment by asottile** [comment]
`--install-types` [is not supported](https://github.com/pre-commit/mirrors-mypy/issues/50#issuecomment-859261537) and pre-commit.ci does not allow access to the network at runtime

the correct way to fix this is `additional_dependencies: [types-toml]` or if you want a hammer I created [types-all](https://github.com/asottile/types-all) to restore backwards compatibility with old typeshed

**Comment by sebhmg** [comment]
`additional_dependencies: [types-toml]` just works. Thank you!
