### ISSUE TITLE
400 error when requesting permission

### ISSUE THREAD

**Issue by graingert** [pre-commit-ci/issues#70]
Screenshot to follow....

**Comment by graingert** [comment]
![image](https://user-images.githubusercontent.com/413772/126212343-e3b5fa69-ab71-42f5-9aac-19455a970a6e.png)

**Comment by asottile** [comment]
I opened a support issue with github -- looks like someone else has seen this as well https://stackoverflow.com/q/68347504/812183

going to wait to see what they say before adding a special-case redirect (in theory I could redirect to either the login url or the homepage -- but I want to confirm that this is or isn't a bug)

**Comment by asottile** [comment]
github has fixed this! 🎉
