### ISSUE TITLE
run pre-commit on all branches, not only on the default one

### ISSUE THREAD

**Issue by sebhmg** [pre-commit-ci/issues#73]
pre-commit.ci appears to run only on the default github branch. I wish it runs upon commit on any branch were  `.pre-commit-config.yaml` is present.

Possibly, also have the option to define in the config file the list of branches to run on, the same way we can in a github workflow yaml file.

**Comment by asottile** [comment]
this is intentionally not done as it doubles pull requests

**Comment by sebhmg** [comment]
assuming code changes always go through a pull request. But granted, that is a fair assumption...  😉
