### ISSUE TITLE
can't run GHA builds that pre-commit triggers in pull requests

### ISSUE THREAD

**Issue by graingert** [pre-commit-ci/issues#74]
eg I've had pre-commit.ci installed in `https://github.com/celery/celery` but we've yet to receive our autoupdate PR. As such any PR that has a `pre-commit` autofix commit pushed to it won't run GHA workflows

**Comment by graingert** [comment]
I'd like to be able to trigger pre-commit CI to push some PR so we can get it merged and add pre-commit.ci as a contributor

**Comment by asottile** [comment]
sorry there's nothing I can do about this -- you'll get your PR eventually
