### ISSUE TITLE
Badge configuration (or API)?

### ISSUE THREAD

**Issue by peterjc** [pre-commit-ci/issues#81]
I just discovered https://pre-commit.ci/ today while exploring caching options on CircleCI and/or GitHub actions to speed up running ``pre-commit run -a`` as part of my Continuous Integration.

This seems both much faster and much easier! Very nice! ❤️  

However, I would like to tweak the badges, as by default I find them rather wide:

<img src="https://camo.githubusercontent.com/b8ae51b6ed398463ba75ba56ea3187a06ed4091dd59da88ecda5f4614e82f2b7/68747470733a2f2f726573756c74732e7072652d636f6d6d69742e63692f62616467652f6769746875622f44616e69656c4a536f7474696c652f706f6b657465616d732d636c69656e742f6d61737465722e737667"> <img src="https://results.pre-commit.ci/badge/github/asottile/demo/main.svg">

Could you offer variants like just the "P" logo and status?

Or, is there an API which could be used by a service like https://shields.io/ (which has the further advantage of perfectly matching badge styles)? If so I would happily open a badge request with them: https://github.com/badges/shields/issues

**Comment by asottile** [comment]
I'd rather maintain brand consistency, if a paid user requests an api or customized badges then I may implement it but for now I'd rather not.

**Comment by peterjc** [comment]
OK, that's reasonable.

And is there any kind of REST API for a project status (per branch ideally), which could be used by Shields or any 3rd party dashboard etc?
