### ISSUE TITLE
Change badge wording from "passed" to "passing"

### ISSUE THREAD

**Issue by peterjc** [pre-commit-ci/issues#82]
Currently on successful runs, pre-commit.ci uses the wording "passed" (which is actually accurate as it reports the latest finished test), while most other services use "passing" instead.

Example with pre-commit.ci  and two badges from Shields.io:

<img width="361" alt="Screenshot 2021-08-26 at 15 52 31" src="https://user-images.githubusercontent.com/63959/130987078-d74f39b4-b22a-4e32-aaa1-a872aed97513.png">

See also:

https://docs.readthedocs.io/en/stable/badges.html

https://docs.travis-ci.com/user/status-images/

https://circleci.com/docs/2.0/status-badges/ (for their shield style)

https://www.appveyor.com/docs/status-badges/ (they have configurable status text, see also #81)

**Comment by peterjc** [comment]
P.S. I've not checked as many badges, but I think the consensus is on error is "failing" in red.

**Comment by peterjc** [comment]
Also GitHub Actions uses "passing" and "failing":

https://docs.github.com/en/actions/managing-workflow-runs/adding-a-workflow-status-badge

**Comment by asottile** [comment]
circle ci, azure pipelines, and gitlab uses "passed" -- "passed" / "failed" / "errored" is also consistent with how pre-commit.ci displays run results

**Comment by peterjc** [comment]
Fair enough - the CI badges are not as one-sided on this naming divide as I thought.
