### ISSUE TITLE
Enhancement request: Offer autoupdate_schedule never/off

### ISSUE THREAD

**Issue by peterjc** [pre-commit-ci/issues#83]
Quoting the configuration documentation here: https://pre-commit.ci/#configuration-autoupdate_schedule

> autoupdate_schedule
> (optional, default: 'weekly') control when the autoupdate runs, possible values: 'weekly', 'monthly', 'quarterly'.`

Could this also support 'never' or 'off' as a way to disable the autoupdates please?

(I anticipate with larger projects being able to adopt the bot functionality gradually would ease adoption.)

**Comment by asottile** [comment]
the more disparate the versions are the worse pre-commit.ci performs and the more expensive it is to operate.  this will not be implemented

**Comment by peterjc** [comment]
Ah, you mean the cost/benefits for the central dependency caching. OK, that does make sense. Thanks.

**Comment by Borda** [comment]
well on the other hand it forces to keep the particular repo up-to-date - the update creates new PR which triggers other CI which for its own build usually pulls the latest packages (dependencies) and eventually fails for future compatibility issues... this yields that the repo author will remove this pre-commit CI or mark the project as archived... is it desired behaviour?

**Comment by asottile** [comment]
sounds like the "continuous" part of CI doing its job to me!

**Comment by Borda** [comment]
> sounds like the "continuous" part of CI doing its job to me!

kind of, so remove the CI when you do not want to have spamming contributor/bot :rabbit: 
btw, how about the eventual demanding resources (pre-commit.ci performs and the more expensive it is to operate) differ if a repo user will close/refuse all auto-updates PRs and still preserve very old versions, it will be in the end the same, right?

**Comment by asottile** [comment]
in that scenario the user would have to be actively working against the system

**Comment by Borda** [comment]
> in that scenario the user would have to be actively working against the system

Actually not actively but passively, just to hang such PRs till stale bot closes them =D

**Comment by asottile** [comment]
look, if you want the feature and you're a paying customer I'll implement it -- I'm not going to build features which intentionally make the system more expensive to run -- I think you can understand that

**Comment by Borda** [comment]
@asottile very appreciate all your work and providing this great CI! :hugs:

**Comment by blakeNaccarato** [comment]
I see your rationale to disallow autoupdate disabling is related to caching costs, and that you would prefer enough paying customers to request this before implementing. However, there are other ways to bump pre-commit dependencies, and I am using one of them via [Renovate](https://docs.renovatebot.com/). This allows me to more granularly update my pre-commit deps, in case one of them is causing issues. So I am still keeping my deps pretty close to the latest versions, just in my own way.

I understand the rationale to keep weekly autoupdate the _default_ for this tool, but how much real cost would be incurred by introduction the _option_ to disable autoupdate? I don't think it would increase the cost of doing business that much if it's behind a config that the majority of users will never touch? Of course, I'm arguing my side and so I may have some bias to think this will be the case, but I really don't think a `disable` flag will induce that much extra running cost.

I think a reasonable middle-ground would be to make this option available, but the vast majority of your install base could still use the defaults. A further bridge would be to allow disabling of autoupdate, but punish/de-prioritize Action runs for users with too many old deps (allowing for some wiggle room), but this would probably be more trouble than it's worth.

Perhaps if this issue starts getting more heat/interest, it might be worthwhile to pin it and check for thumbs-ups as a gauge of the level of interest in this feature. Perhaps it really is just a few tooling-obsessed weirdos like me crying out, but I do think it would be nice to have this option.
