### ISSUE TITLE
`repo: meta`: `check-hooks-apply` leads to: Read-only file system: '/pc/.lock'

### ISSUE THREAD

**Issue by billsioros** [pre-commit-ci/issues#84]
The `check-hooks-apply` meta hook raise the aforementioned error on the CI. The relevant run is shown [here](https://results.pre-commit.ci/run/github/397328294/1630096200.gc0yUTEhQjWXHyWTTGOpfQ).

**Comment by asottile** [comment]
weird! I will look into this and try and get a good for you!

**Comment by asottile** [comment]
this ended up being quite the interesting thing to track down

it turns out it was trying to lint a `.pre-commit-config.yaml` file separate from the actual configuration -- so I've fixed this in pre-commit/pre-commit#2026 and rolled this out to the CI fleet -- thanks again for the report!
