### ISSUE TITLE
Feature request: Link to GitHub repo from pre-commit.ci repo page

### ISSUE THREAD

**Issue by peterjc** [pre-commit-ci/issues#85]
1. Goto a branch status page, e.g. https://results.pre-commit.ci/latest/github/asottile/pyupgrade/master

<img width="495" alt="Screenshot 2021-08-30 at 10 18 44" src="https://user-images.githubusercontent.com/63959/131317019-1c547ba1-5622-4c15-8754-4688e111297b.png">

2. Notice the "breadcrumbs" for "asottile / pyupgrade · master" are three links to the user on pre-commit.ci, the repository on pre-commit.ci, and the master branch on GitHub.

3. Click on the repository name, here "pyupgrade" https://results.pre-commit.ci/repo/github/83462592

<img width="493" alt="Screenshot 2021-08-30 at 10 18 35" src="https://user-images.githubusercontent.com/63959/131317042-03c988b6-d3b8-4290-9593-ec4c5a9f2325.png">

4. Notice only one of the two "breadcrumbs" are links: "asottile / pyupgrade", just the user on pre-commit.ci

Expected behaviour: repository name is still a link, this time to GitHub

Workaround: click on any branch, from there can click to the branch on GitHub, and change to the default branch if desired

Use case: Exploring other people's pre-commit.com configuration files by browsing usage on pre-commit.ci

**Comment by asottile** [comment]
the branch icon goes to github

**Comment by peterjc** [comment]
Yes, as in the first page / screenshot.

I'm asking about the second page / screenshot - how to get to the GitHub repo from there.

**Comment by asottile** [comment]
there's now a small link to the repository (via the icon next to the name) on the repo page!

thanks again for the issue

**Comment by peterjc** [comment]
Lovely, thank you.
