### ISSUE TITLE
Integrate pre-commit.ci into pre-commit CLI

### ISSUE THREAD

**Issue by janosh** [pre-commit-ci/issues#87]
Would be nice if repos could be added to pre-commit.ci and managed thereafter without having to use the web interface. Perhaps the way to do this would be adding a `ci` command to the `pre-commit` CLI? So in a repo with `pre-commit` hooks that's not yet registered with pre-commit.ci yet, I would run

```sh
pre-commit ci add
```
to enable pre-commit.ci and

```sh
pre-commit ci remove
```

to unregister.

**Comment by asottile** [comment]
there isn't an api to add a github app so it would only work if you've already enabled the app for your user / org

and it would need to get a github api token from somewhere and I don't really want to be responsible for credential management
