### ISSUE TITLE
Feature: make the integration opt-in by the config presence

### ISSUE THREAD

**Issue by webknjaz** [pre-commit-ci/issues#88]
This integration was added to @aio-libs by one of the admins and it started confusing people contributing to the repositories that don't have `pre-commit` integrated. Example: https://results.pre-commit.ci/run/github/33274959/1630934472.AmVMdercTiGFghs-_41GYQ.

A workaround would be to manually list repos the service has access to but this seems to be a bad UX. It's hard to manage such things when an org has a lot of repos.

Instead, I suggest treating the presence of `.pre-commit-config.yaml` as an explicit opt-in and not report anything via Checks API or at least report a neutral status (not an error). As a middle ground, maybe it would reasonable to do this only if an org allows access to all repos, without a manual selection.

**Comment by asottile** [comment]
it costs me money to have webhooks sent to me that are meaningless so I'm going to continue to issue an error response for missing configurations to encourage users to turn it off

also someone could easily mistakenly rename the file and silently disable their CI which seems not good

**Comment by webknjaz** [comment]
I see. But FTR the opt-in is something that other CIs do.

**Comment by asottile** [comment]
some also error on incorrect configuration and that is what I have chosen to do
