### ISSUE TITLE
Cargo support

### ISSUE THREAD

**Issue by hombit** [pre-commit-ci/issues#89]
Please can you add a recent Rust toolchain to CI workers

**Comment by asottile** [comment]
it is available for any `language: rust` hook

**Comment by hombit** [comment]
Thank you! I'm trying to use [these hooks](https://github.com/doublify/pre-commit-rust), which just call cargo command with `language: system`. These hooks cause "Executable `cargo` not found" error on pre-commit.ci. So I don't need `rust` to compile hook itself, but I need `cargo` to run formatting and linter

**Comment by asottile** [comment]
you may have better luck with `repo: local` versions of those that have `language: rust` ?
