### ISSUE TITLE
Badge target page does not tell you nothing has been run yet.

### ISSUE THREAD

**Issue by jhulten** [pre-commit-ci/issues#9]
to repro:

- Add repository to p-c.ci
- Before pushing anything, click on the badge (should be labeled `unknown`)
- Link to `/latest/github/<user_or_org>/<repo>/<default_branch>` will reply "Not found"

**Comment by asottile** [comment]
indeed, I need to improve the blank-state pages

I'll probably add some messaging about not having any runs yet 👍

**Comment by asottile** [comment]
the never-run badge now redirects to the repository page if a run has never occurred -- thanks again for the issue!
