### ISSUE TITLE
Artifacts for code coverage?

### ISSUE THREAD

**Issue by janosh** [pre-commit-ci/issues#93]
Can/will pre-commit.ci store artifacts? Could it be used to keep track of code coverage?

I'm guessing not in which case might I ask the off-topic question of which service you recommend instead? You seem to prefer Azure Dev Ops over Codecov and Coveralls? Reasons for that?

**Comment by asottile** [comment]
pre-commit.ci as it is right now won't be a coverage system -- I do plan at some point to maybe write my own coverage system but that'll be ~somewhat separate (it might reuse the domain and some of the github app logic but it'll likely exist as a separate entity)

as for my preference for coverage systems -- I basically just use whatever is the simplest.  azure devops has builtin coverage so it's kinda nice -- though I'm looking to move off of it at some point.  I've used coveralls in the past, but I stopped when they had some scaling issues at some point.  personally I'd like to stay away from codecov, my experience with it has not been great -- very slow, often not helpful results, and they had that big scary breach a while back too 🤷
