### ISSUE TITLE
Feature request: add python 3.10 support

### ISSUE THREAD

**Issue by mayeut** [pre-commit-ci/issues#94]
The runner image is lacking python 3.10 support:
https://results.pre-commit.ci/run/github/253221368/1633790576.YJzWa7ARQtayziAdRV7gvg

**Comment by asottile** [comment]
should be live in prod now!

**Comment by mayeut** [comment]
Working fine now: https://results.pre-commit.ci/run/github/253221368/1633796302.YJLsEn9nSD6dy2ZyVuk_9w
Thanks !
