### ISSUE TITLE
Responsive reaction to `pre-commit.ci run`

### ISSUE THREAD

**Issue by webknjaz** [pre-commit-ci/issues#95]
I've used `pre-commit.ci run` today and didn't see any difference in the checks list or in the comments. It took me a while to realize that I could compare the timestamp on the check run and to see that it correlates with the comment.

My suggestion is to follow what other bots do and add an :eyes: reaction to the comments with the command to signal that pre-commit.ci actually received and recognized it.

**Comment by asottile** [comment]
dupe #75
