### ISSUE TITLE
autoupdate did not run for one repo

### ISSUE THREAD

**Issue by adamchainz** [pre-commit-ci/issues#97]
My private repo `adamchainz/book-django-dx` is configured with pre-commit.ci. This repo did not receive an autoupdate PR last night for the new version of Black, as I did on my other repos.

The only unique thing I can think of for this repo is that it has never had *any* pull requests made against it... I only push on `main`, but I do see pre-commit.ci verifying such commits.

**Comment by asottile** [comment]
very strange -- for some reason the `install` for your account missed a webhook from github's side at some point and hadn't updated your repositories

I've manually sync'd them for now and I'm looking into whether there's something further broken -- but it should receive an update next week -- let me know if you'd like me to manually trigger this week's update on that repo as well

**Comment by adamchainz** [comment]
Thanks for looking into it. No need for the update, I can run it manually.

**Comment by asottile** [comment]
thanks for the report!
