### ISSUE TITLE
Manual re-queue button

### ISSUE THREAD

**Issue by janosh** [pre-commit-ci/issues#98]
Sometimes pre-commit.ci seems to fail for random reasons (like manual DB edits 😄). GitHub Actions has a manual re-run button for such cases. Avoids the need to push again to verify pre-commit.ci status is actually fine.

![Screen Shot 2021-11-10 at 21 13 31](https://user-images.githubusercontent.com/30958850/141194784-65c4e4e9-7017-42ce-90a6-0abffd8f25a3.png)

**Comment by asottile** [comment]
you can comment `pre-commit.ci run` on any PR as documented in https://pre-commit.ci

**Comment by janosh** [comment]
I don't use PRs on my own repos.

**Comment by asottile** [comment]
I don't want to add such a button because it is easy to abuse

**Comment by janosh** [comment]
Doesn't `pre-commit.ci run` have the same potential for abuse?

**Comment by asottile** [comment]
nope! github's abuse mechanisms shield us
